"""
Curated semantic differential: the port's ``--nft`` vs kernel iptables-nft.

The port's existing nft guarantees are all self-referential: golden pairs
pin ``--nft`` output against a frozen expectation, ``nft -c`` proves it is
valid, and the readback e2e proves it round-trips through the kernel
byte-for-byte.  None of them prove the emitted nft *means* the same thing
as the iptables rule it came from -- a ``--dport`` mistranslated to
``sport`` would round-trip happily.

This suite closes exactly that gap for the core match/target vocabulary
by diffing against an independent translator: ``iptables-nft-restore``,
the kernel's own iptables->nft compatibility path.  For each curated
config both routes are driven into a throwaway network namespace --

    ferm --nft         -> nft -f            -> nft list ruleset   (A)
    ferm (iptables)    -> iptables-nft      -> nft list ruleset   (B)

-- and A and B are required equal after :mod:`normalize` folds away the
surface conventions that differ between the two (counters, the
``ip protocol`` vs ``meta l4proto`` dispatch spelling, hex width, the
default limit burst, set/flag ordering, the port's single-table chain
prefixing).

Scope is deliberately narrow and honest about its blind spots:

* only the subset iptables-nft translates *natively* is here; matches it
  blackholes into an opaque ``xt match "..."`` blob (``osf``, ``recent``,
  ...) yield no cross-check and are excluded -- those are covered instead
  by the readback e2e.  A curated case that ever starts blobbing fails
  loudly (see ``_assert_no_blob``) rather than silently degrading.
* every config is *scalar*: no arrays.  The port collapses arrays into
  nft sets while the iptables path unfolds them into a cartesian product
  of rules, so a set-carrying config diverges at rule granularity, not
  semantics -- out of scope for a per-rule diff.

Opt-in only by tooling: it runs in the ordinary suite wherever a rootless
network namespace, ``nft`` and ``iptables-nft-restore`` are available, and
skips cleanly otherwise -- the same graceful degradation the corpus nft
gate uses.
"""

from __future__ import annotations

import functools
import re
import shutil
import subprocess
from typing import TYPE_CHECKING

import pytest

from tests._oracle import PORT_FERM, spawn_ferm
from tests.e2e.iptables_nft.normalize import _TABLE_CONCEPTS, parse_dump

if TYPE_CHECKING:
    from pathlib import Path

#: Lines the nft backend emits into ``--lines`` output that make up the
#: ruleset fed to ``nft -f``; the ``@hook`` command echoes around them
#: are not part of it.
_NFT_LINE = re.compile(r"^(add|create|delete|insert|flush|replace) ")

#: The per-family banner the iptables backend prints ahead of each
#: ``iptables-save`` block; the tag names the restore tool for that block.
_BANNER = re.compile(r"^# Generated by ferm .*\((?P<tool>[a-z0-9-]+)-save\)")

#: iptables-save banner tag -> the nft-backed restore binary for it.
_RESTORE_FOR = {
    "iptables-legacy": "iptables-nft-restore",
    "ip6tables-legacy": "ip6tables-nft-restore",
}


@functools.cache
def _iptables_nft_usable() -> bool:
    """Probe for a rootless netns plus the nft-backed iptables tools."""
    needed = [
        "unshare",
        "nft",
        "iptables-nft-restore",
        "ip6tables-nft-restore",
    ]
    if any(shutil.which(tool) is None for tool in needed):
        return False
    try:
        probe = subprocess.run(
            ["unshare", "-rn", "nft", "list", "ruleset"],
            capture_output=True,
            check=False,
            timeout=10,
        )
    except (OSError, subprocess.TimeoutExpired):
        return False
    return probe.returncode == 0


pytestmark = pytest.mark.skipif(
    not _iptables_nft_usable(),
    reason="needs rootless unshare + nft + iptables-nft-restore",
)


def _ferm(config: Path, *nft: str) -> str:
    proc = spawn_ferm(
        PORT_FERM, [*nft, "--noexec", "--lines", str(config)], check=True
    )
    return proc.stdout


def _netns_dump(setup: str) -> str:
    """Run *setup* then ``nft list ruleset`` in a fresh rootless netns."""
    proc = subprocess.run(  # fixed argv, no shell
        ["unshare", "-rn", "bash", "-c", f"set -e; {setup}; nft list ruleset"],
        capture_output=True,
        encoding="utf-8",
        check=False,
        timeout=30,
    )
    assert proc.returncode == 0, f"netns load failed:\n{proc.stderr}"
    return proc.stdout


def _our_nft_dump(config: Path, workdir: Path) -> str:
    lines = _ferm(config, "--nft")
    script = "".join(
        line
        for line in lines.splitlines(keepends=True)
        if _NFT_LINE.match(line)
    )
    assert script, "the port emitted an empty nft ruleset"
    path = workdir / "ours.nft"
    path.write_text(script, encoding="utf-8")
    return _netns_dump(f"nft -f {path}")


def _iptables_nft_dump(config: Path, workdir: Path) -> str:
    lines = _ferm(config)
    blocks: dict[str, list[str]] = {}
    tool: str | None = None
    for line in lines.splitlines(keepends=True):
        banner = _BANNER.match(line)
        if banner:
            tool = _RESTORE_FOR.get(banner.group("tool"))
            continue
        if tool is not None:
            blocks.setdefault(tool, []).append(line)
    setup = []
    for restore, block in blocks.items():
        if not any(entry.strip() for entry in block):
            continue
        path = workdir / f"{restore}.rules"
        path.write_text("".join(block), encoding="utf-8")
        setup.append(f"{restore} < {path}")
    assert setup, "the port emitted no ip/ip6 iptables rules to load"
    return _netns_dump("; ".join(setup))


def _assert_no_blob(dump: str, cid: str) -> None:
    # iptables-nft renders a match/target it cannot natively translate as
    # an opaque ``xt match "name"`` blob, which carries no comparable
    # semantics.  A curated case must exercise only natively-translated
    # vocabulary, so a blob here means the case belongs in the readback
    # suite instead -- fail loudly rather than skip silently.
    blob = "xt match" in dump or "xt target" in dump
    assert not blob, (
        f"curated case {cid!r} blobs on iptables-nft; it is not natively "
        f"translated and must move out of the differential set:\n{dump}"
    )


def _assert_no_concept_chain(dump: str, cid: str) -> None:
    # A filter-table chain literally named with a concept prefix (`nat_x`)
    # collides with the port's concept-prefix encoding: `_table_and_chain`
    # would read it as concept `nat` on the port side while the reference
    # side keeps it under `filter`, so the keys diverge into a phantom diff.
    # Curated cases must avoid such names -- fail loudly at authoring time
    # rather than debug a confusing red diff later.
    table = ""
    for raw in dump.splitlines():
        line = raw.strip()
        if line.startswith("table "):
            table = line.split()[2]
        elif line.startswith("chain ") and table == "filter":
            chain = line.split()[1]
            clash = next(
                (c for c in _TABLE_CONCEPTS if chain.startswith(f"{c}_")),
                None,
            )
            assert clash is None, (
                f"curated case {cid!r} names a filter chain {chain!r} with "
                f"the {clash!r} concept prefix, which `_table_and_chain` "
                f"would misattribute; rename the chain to avoid a phantom diff"
            )


def _filter(rule: str) -> str:
    return f"table filter {{\n\tchain INPUT {{\n\t\t{rule}\n\t}}\n}}\n"


def _filter6(rule: str) -> str:
    body = f"table filter {{\n\t\tchain INPUT {{\n\t\t\t{rule}\n\t\t}}\n\t}}"
    return f"domain ip6 {{\n\t{body}\n}}\n"


def _nat(chain: str, rule: str) -> str:
    return f"table nat {{\n\tchain {chain} {{\n\t\t{rule}\n\t}}\n}}\n"


#: Curated scalar configs, each pinning one core match or target whose
#: nft translation iptables-nft also produces natively.  The port's
#: emission must mean the same thing the kernel's own translator emits.
_CASES: dict[str, str] = {
    # -- ip filter matches --
    "tcp_dport": _filter("proto tcp dport 22 ACCEPT;"),
    "udp_dport": _filter("proto udp dport 53 ACCEPT;"),
    "tcp_sport": _filter("proto tcp sport 1024 ACCEPT;"),
    "tcp_dport_range": _filter("proto tcp dport 1000:2000 ACCEPT;"),
    "ct_state": _filter("mod state state (ESTABLISHED RELATED) ACCEPT;"),
    "ct_invalid": _filter("mod state state INVALID DROP;"),
    "saddr_cidr": _filter("saddr 10.0.0.0/8 ACCEPT;"),
    "daddr_host": _filter("daddr 192.168.1.1 ACCEPT;"),
    "iif_lo": _filter("interface lo ACCEPT;"),
    "proto_only": _filter("proto tcp ACCEPT;"),
    "icmp_type": _filter("proto icmp icmp-type echo-request ACCEPT;"),
    "addrtype_local": _filter("mod addrtype src-type LOCAL ACCEPT;"),
    "multiport": _filter(
        "proto tcp mod multiport source-ports (22 80 443) ACCEPT;"
    ),
    "mark_match": _filter("mod mark mark 0x10 ACCEPT;"),
    "tcp_flags": _filter("proto tcp tcp-flags (SYN ACK RST FIN) SYN ACCEPT;"),
    # -- ip filter targets --
    "target_drop": _filter("proto tcp dport 25 DROP;"),
    "target_reject": _filter(
        "proto tcp dport 25 REJECT reject-with tcp-reset;"
    ),
    "target_mark": _filter("proto tcp dport 25 MARK set-mark 0x10;"),
    # -- ip6 filter --
    "ip6_tcp_dport": _filter6("proto tcp dport 22 ACCEPT;"),
    "ip6_saddr": _filter6("saddr fe80::/10 ACCEPT;"),
    "ip6_icmpv6": _filter6("proto ipv6-icmp icmpv6-type echo-request ACCEPT;"),
    "ip6_ct_state": _filter6("mod state state (ESTABLISHED RELATED) ACCEPT;"),
    # -- ip nat targets --
    "nat_dnat": _nat("PREROUTING", "proto tcp dport 80 DNAT to 10.0.0.1;"),
    "nat_snat": _nat("POSTROUTING", "saddr 10.0.0.0/8 SNAT to 1.2.3.4;"),
    "nat_masquerade": _nat("POSTROUTING", "outerface eth0 MASQUERADE;"),
    "nat_redirect": _nat(
        "PREROUTING", "proto tcp dport 80 REDIRECT to-ports 8080;"
    ),
}


@pytest.mark.parametrize("cid", list(_CASES), ids=list(_CASES))
def test_nft_matches_iptables_nft(cid: str, tmp_path: Path) -> None:
    config = tmp_path / f"{cid}.ferm"
    config.write_text(_CASES[cid], encoding="utf-8")

    ours = parse_dump(_our_nft_dump(config, tmp_path))
    reference_dump = _iptables_nft_dump(config, tmp_path)
    _assert_no_blob(reference_dump, cid)
    _assert_no_concept_chain(reference_dump, cid)
    reference = parse_dump(reference_dump)

    # A curated case must actually exercise a rule on both sides; an empty
    # comparison would pass vacuously and pin nothing.
    compared = [
        key
        for key in ours.keys() | reference.keys()
        if ours.get(key) or reference.get(key)
    ]
    assert compared, f"{cid}: no rules were compared"
    for key in compared:
        assert ours.get(key, []) == reference.get(key, []), (
            f"{cid}: {key} diverges\n"
            f"  --nft        : {ours.get(key, [])}\n"
            f"  iptables-nft : {reference.get(key, [])}"
        )
