# ferm(1) / import-ferm(1) bash completion.
# Generated by tools/gen_completion.py -- do not edit by hand;
# regenerate with `uv run nox -s completion`.
# The array-from-compgen idiom below is the standard completion shape:
# shellcheck disable=SC2207

_ferm() {
    local cur prev
    cur=${COMP_WORDS[COMP_CWORD]}
    prev=${COMP_WORDS[COMP_CWORD-1]}

    if [[ ${COMP_WORDS[1]-} == rollback ]]; then
        case "$prev" in
        --domain) COMPREPLY=($(compgen -W "ip ip6 arp eb" -- "$cur")); return ;;
        esac
        if [[ $cur == -* ]]; then
            COMPREPLY=($(compgen -W "--list --diff --to -n --limit --nft --slow --full-reload --nolegacy -i --interactive -t --timeout --domain --def --no-etckeeper -h --help" -- "$cur"))
        else
            COMPREPLY=($(compgen -f -- "$cur"))
        fi
        return
    fi

    case "$prev" in
        --domain) COMPREPLY=($(compgen -W "ip ip6 arp eb" -- "$cur")); return ;;
        --graph-format) COMPREPLY=($(compgen -W "dot d2" -- "$cur")); return ;;
        --lint-fail-level) COMPREPLY=($(compgen -W "error warning info" -- "$cur")); return ;;
        --plan-format) COMPREPLY=($(compgen -W "structured diff" -- "$cur")); return ;;
    esac

    if [[ $cur == -* ]]; then
        COMPREPLY=($(compgen -W "-n --noexec -F --flush --noflush -l --lines -i --interactive -t --timeout -h --help -V --version --test --remote --test-mock-previous --fast --slow --shell --domain --def --nolegacy --nft --full-reload --no-etckeeper --plan --plan-format --lint --lint-strict --lint-fail-level --list-modules --describe --graph --graph-format" -- "$cur"))
    elif [[ $COMP_CWORD -eq 1 ]]; then
        COMPREPLY=($(compgen -W "rollback" -- "$cur")
            $(compgen -f -- "$cur"))
    else
        COMPREPLY=($(compgen -f -- "$cur"))
    fi
}
complete -F _ferm ferm

_import_ferm() {
    local cur
    cur=${COMP_WORDS[COMP_CWORD]}
    if [[ $cur == -* ]]; then
        COMPREPLY=($(compgen -W "-h --help" -- "$cur"))
    else
        COMPREPLY=($(compgen -f -- "$cur"))
    fi
}
complete -F _import_ferm import-ferm
