"""Faithful Python port of ``reference/test/sort.pl``.

ferm emits tables and chains in random order (Perl hash ordering), so
the golden suite canonicalizes both sides before diffing.  This is NOT a
line sort: it groups lines under a key built from
``(family, table, chain)`` and prints the groups ordered by key, keeping
each group's internal line order intact.  The ``z``-suffixes in the keys
force ``*table`` headers, rule lines and ``COMMIT`` into a deterministic
relative order within one table.

The behaviour mirrors the Perl original line for line; see that file for
the authoritative reference.
"""

from __future__ import annotations

import re

# A "# Generated by ferm <ver> (<tool>) on <date>" banner: keep everything
# up to " on ..." so the volatile timestamp drops out, and flush the
# accumulated groups (a banner starts a fresh save block).
_BANNER = re.compile(r"^(# Generated .+) on .+")

# "<fam>tables -t <table> -N|A|P <chain>" — chain creation / append /
# policy lines in iptables-save and slow-mode command output.
_NAP = re.compile(r"^(\w+)tables -t (\w+) -([NAP]) (\S+)")

# "<fam>tables [--atomic-file X] -t <table> -F|X" — flush / delete-chain.
# The trailing "()" captures an empty chain so the key logic below can
# treat it uniformly with the NAP case.
_FX = re.compile(r"^(\w+)tables(?: --atomic-file \w+)? -t (\w+) -([FX])()$")

_TABLE = re.compile(r"^\*(\S+)")
_CHAIN = re.compile(r"^(:)(\S+)")
_APPEND = re.compile(r"^-(A) (\S+)")
# "ebtables -t <table> --atomic-file <path> <rest>" — atomic-file commands
# are grouped by their atomic-file path (the second capture).
_EB_ATOMIC = re.compile(r"^ebtables -t (\w+) --atomic-file (\S+) [^\n]+")


def sort_output(text: str) -> str:
    """Canonicalize ferm output the way ``sort.pl`` does.

    Raises ``ValueError`` on any line the Perl original would ``die`` on,
    so harness drift surfaces loudly instead of silently dropping lines.
    """
    rules: dict[str, list[str]] = {}
    table: str | None = None
    out: list[str] = []

    def flush() -> None:
        nonlocal table, rules
        for key in sorted(rules):
            out.extend(rules[key])
        rules = {}
        table = None

    for line in text.splitlines(keepends=True):
        banner = _BANNER.match(line)
        if banner:
            flush()
            out.append(banner.group(1) + "\n")
            continue
        if line.startswith("#"):
            continue

        nap = _NAP.match(line)
        flush_chain = _FX.match(line)
        if nap or flush_chain:
            match = nap or flush_chain
            assert match is not None
            fam, tbl, action, chain = match.group(1, 2, 3, 4)
            key = (
                f"{fam} {tbl}  {chain}"
                if action == "P"
                else f"{fam} {tbl} {chain}"
            )
            if chain == "":
                key += " z"
            rules.setdefault(key, []).append(line)
            continue

        star = _TABLE.match(line)
        if star:
            # Bind a fresh local: ``table`` is nonlocal-captured by
            # ``flush`` and so stays widened to ``str | None``.
            table_name: str = star.group(1)
            table = table_name
            rules.setdefault(table_name, []).append(line)
            continue

        if line.startswith("COMMIT"):
            rules.setdefault(f"{table}z", []).append(line)
            continue

        chain_line = _CHAIN.match(line) or _APPEND.match(line)
        if chain_line:
            key = f"{table}{chain_line.group(1)}{chain_line.group(2)}"
            rules.setdefault(key, []).append(line)
            continue

        eb = _EB_ATOMIC.match(line)
        if eb:
            rules.setdefault(eb.group(2), []).append(line)
            continue

        raise ValueError(f"sort.pl: unrecognized line: {line!r}")

    flush()
    return "".join(out)
