"""Canonicalize whole-run ferm output for cross-implementation diffs.

Shared by the corpus suite and the grammar-based config fuzzer
(:mod:`tests.property.test_config_differential`): both compare the
Python port against the Perl oracle on entire configurations, where
tables/chains come out in Perl-hash order, the banner carries the
implementation's own version string, and ebtables atomic-file names are
random.
"""

from __future__ import annotations

from tests.golden.normalize import ebtables_tempfile_rename
from tests.golden.sortpl import is_save_line, sort_output


def canonicalize(text: str) -> str:
    """Make ferm output comparable across implementations and runs."""
    text = ebtables_tempfile_rename(text)
    out: list[str] = []
    block: list[str] = []

    def flush_block() -> None:
        out.append(sort_output("".join(block)))
        block.clear()

    for line in text.splitlines(keepends=True):
        banner = line.startswith("# Generated by ferm ")
        if banner:
            # Both the version and the timestamp vary; sort_output only
            # drops the timestamp, so reduce the banner to its constant
            # prefix before grouping.
            line = "# Generated by ferm on x\n"  # noqa: PLW2901
        if banner or is_save_line(line):
            block.append(line)
        else:
            flush_block()
            out.append(line)
    flush_block()
    return "".join(out)
