"""
Differential end-to-end run of real-world configs: port vs oracle.

Every corpus config (see ``README.md`` for provenance) plus the upstream
``reference/examples/`` set is compiled by both the frozen Perl oracle
and the Python port with ``--test --noexec --lines``, in fast and slow
mode.  The two implementations must agree bug-for-bug:

* the exit verdict (success vs failure) must match -- the exact failing
  status is not compared, since Perl's ``die`` exits with whatever
  ``$!`` happens to hold;
* stderr must match byte-for-byte (warnings and diagnostics);
* stdout must match after canonicalization: tables/chains come out in
  Perl-hash order on the oracle side (``sort.pl`` grouping), the random
  ebtables ``/tmp/ferm.XXXX`` atomic-file names are renamed, and the
  version inside the ``# Generated by ferm ...`` banner is dropped.

Unlike ``sort.pl`` the canonicalizer (:mod:`tests.corpus.canon`) must
survive ``@hook`` command lines, which ``--lines`` prints among the save
blobs: unrecognized lines pass through in positional order and only the
save blocks around them are sorted.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from tests._oracle import (
    PORT_FERM,
    assert_oracle_parity,
    compile_config,
    oracle_ferm,
)
from tests.corpus.canon import canonicalize

pytestmark = pytest.mark.usefixtures("require_perl")

_HERE = Path(__file__).resolve().parent
REPO_ROOT = _HERE.parents[1]
CONFIGS = _HERE / "configs"
TRANSLATED = _HERE / "translated"
EXAMPLES = REPO_ROOT / "reference" / "examples"

#: ``examples/resolve.ferm`` is excluded in place: its mock zonefile must
#: sit next to the config and the reference tree is frozen, so the corpus
#: carries a copy (``upstream-resolve.ferm``) with its own zonefile.
_EXCLUDED_EXAMPLES = {"resolve.ferm"}


def flat_and_nested_configs(root: Path) -> list[Path]:
    """
    Flat ``*.ferm`` files plus each subdir's same-named entry file.

    The multi-file convention: a config directory holds an entry file named
    after it, with its @include targets beside it (resolved relative to the
    entry file by both implementations).  A directory without that
    same-named entry file fails loudly downstream (FileNotFoundError), by
    design -- never silently skipped.
    """
    flat = sorted(root.glob("*.ferm"))
    nested = sorted(
        path / f"{path.name}.ferm"
        for path in root.iterdir()
        if path.is_dir() and not path.name.startswith(".")
    )
    return flat + nested


def _corpus_configs() -> list[Path]:
    # Hand-translated adversarial configs (see translated/ headers):
    # real-world iptables/nft setups rewritten into ferm to stress
    # unusual structure -- chain mazes, multi-stage NAT, raw/mangle.
    translated = sorted(TRANSLATED.glob("*.ferm"))
    upstream = sorted(
        path
        for path in EXAMPLES.glob("*.ferm")
        if path.name not in _EXCLUDED_EXAMPLES
    )
    return flat_and_nested_configs(CONFIGS) + translated + upstream


@pytest.mark.parametrize("mode_args", [[], ["--slow"]], ids=["fast", "slow"])
@pytest.mark.parametrize(
    "config", _corpus_configs(), ids=lambda path: path.stem
)
def test_corpus_config_matches_oracle(
    config: Path, mode_args: list[str], perl_has_resolver_mock: bool
) -> None:
    if "resolve" in config.name and not perl_has_resolver_mock:
        pytest.skip("Net::DNS::Resolver::Mock not installed")

    args = ["--test", "--noexec", "--lines", *mode_args, str(config)]
    oracle = compile_config(oracle_ferm(REPO_ROOT), args)
    port = compile_config(PORT_FERM, args)

    assert_oracle_parity(port, oracle, canonicalize)
