"""Differential end-to-end run of real-world configs: port vs oracle.

Every corpus config (see ``README.md`` for provenance) plus the upstream
``reference/examples/`` set is compiled by both the frozen Perl oracle
and the Python port with ``--test --noexec --lines``, in fast and slow
mode.  The two implementations must agree bug-for-bug:

* the exit verdict (success vs failure) must match -- the exact failing
  status is not compared, since Perl's ``die`` exits with whatever
  ``$!`` happens to hold;
* stderr must match byte-for-byte (warnings and diagnostics);
* stdout must match after canonicalization: tables/chains come out in
  Perl-hash order on the oracle side (``sort.pl`` grouping), the random
  ebtables ``/tmp/ferm.XXXX`` atomic-file names are renamed, and the
  version inside the ``# Generated by ferm ...`` banner is dropped.

Unlike ``sort.pl`` the canonicalizer must survive ``@hook`` command
lines, which ``--lines`` prints among the save blobs: unrecognized lines
pass through in positional order and only the save blocks around them
are sorted.
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

import pytest

from tests.golden.normalize import ebtables_tempfile_rename
from tests.golden.sortpl import is_save_line, sort_output

_HERE = Path(__file__).resolve().parent
REPO_ROOT = _HERE.parents[1]
CONFIGS = _HERE / "configs"
EXAMPLES = REPO_ROOT / "reference" / "examples"

#: ``examples/resolve.ferm`` is excluded in place: its mock zonefile must
#: sit next to the config and the reference tree is frozen, so the corpus
#: carries a copy (``upstream-resolve.ferm``) with its own zonefile.
_EXCLUDED_EXAMPLES = {"resolve.ferm"}

_ENV = {**os.environ, "LC_ALL": "C", "LANG": "C"}


def _corpus_configs() -> list[Path]:
    wild = sorted(CONFIGS.glob("*.ferm"))
    upstream = sorted(
        path
        for path in EXAMPLES.glob("*.ferm")
        if path.name not in _EXCLUDED_EXAMPLES
    )
    return wild + upstream


def canonicalize(text: str) -> str:
    """Make ferm output comparable across implementations and runs."""
    text = ebtables_tempfile_rename(text)
    out: list[str] = []
    block: list[str] = []

    def flush_block() -> None:
        out.append(sort_output("".join(block)))
        block.clear()

    for line in text.splitlines(keepends=True):
        banner = line.startswith("# Generated by ferm ")
        if banner:
            # Both the version and the timestamp vary; sort_output only
            # drops the timestamp, so reduce the banner to its constant
            # prefix before grouping.
            line = "# Generated by ferm on x\n"  # noqa: PLW2901
        if banner or is_save_line(line):
            block.append(line)
        else:
            flush_block()
            out.append(line)
    flush_block()
    return "".join(out)


def _compile(prefix: tuple[str, ...], args: list[str]) -> tuple[
    bool, str, str
]:
    proc = subprocess.run(  # fixed argv, no shell
        [*prefix, *args],
        capture_output=True,
        text=True,
        check=False,
        env=_ENV,
        cwd=REPO_ROOT,
    )
    return proc.returncode == 0, proc.stdout, proc.stderr


@pytest.mark.parametrize(
    "mode_args", [[], ["--slow"]], ids=["fast", "slow"]
)
@pytest.mark.parametrize(
    "config", _corpus_configs(), ids=lambda path: path.stem
)
def test_corpus_config_matches_oracle(
    config: Path, mode_args: list[str], perl_has_resolver_mock: bool
) -> None:
    if "resolve" in config.name and not perl_has_resolver_mock:
        pytest.skip("Net::DNS::Resolver::Mock not installed")

    args = ["--test", "--noexec", "--lines", *mode_args, str(config)]
    oracle = _compile(("perl", str(REPO_ROOT / "reference" / "src" / "ferm")), args)
    port = _compile((sys.executable, "-m", "pyferm"), args)

    assert port[0] == oracle[0], f"exit verdict differs\n{port[2]}{oracle[2]}"
    assert port[2] == oracle[2], "stderr differs"
    assert canonicalize(port[1]) == canonicalize(oracle[1])
