"""
Generate packaging/completions/ferm.bash from the cli_doc table.

Option names and the subcommand come from the curated
``pyferm.cli_doc`` table; ``choices`` values are read live from the
built argparse parsers, so a drifted value cannot be emitted.
``--domain`` is a free string in argparse and its completion values
are curated here.  The output is committed; ``nox -s completion``
regenerates it and a unit gate diffs (no skip: pure python).

Lives outside ``src/`` on purpose: a tool may import both ``cli`` and
``cli_doc`` (import-linter does not check scripts).
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Final

from pyferm import cli_doc
from pyferm.cli import _build_parser, _build_rollback_parser

_OUTPUT: Final[Path] = (
    Path(__file__).resolve().parent.parent
    / "packaging"
    / "completions"
    / "ferm.bash"
)

#: --domain has no argparse choices (a free string); completion offers
#: the known families.  Curated -- keep in sync with pyferm.domains.
_DOMAIN_VALUES: Final[str] = "ip ip6 arp eb"

_TEMPLATE: Final[str] = """\
# ferm(1) / import-ferm(1) bash completion.
# Generated by tools/gen_completion.py -- do not edit by hand;
# regenerate with `uv run nox -s completion`.
# The array-from-compgen idiom below is the standard completion shape:
# shellcheck disable=SC2207

_ferm() {
    local cur prev
    cur=${COMP_WORDS[COMP_CWORD]}
    prev=${COMP_WORDS[COMP_CWORD-1]}

    if [[ ${COMP_WORDS[1]-} == rollback ]]; then
        case "$prev" in
@ROLLBACK_CASES@
        esac
        if [[ $cur == -* ]]; then
            COMPREPLY=($(compgen -W "@ROLLBACK_FLAGS@" -- "$cur"))
        else
            COMPREPLY=($(compgen -f -- "$cur"))
        fi
        return
    fi

    case "$prev" in
@MAIN_CASES@
    esac

    if [[ $cur == -* ]]; then
        COMPREPLY=($(compgen -W "@MAIN_FLAGS@" -- "$cur"))
    elif [[ $COMP_CWORD -eq 1 ]]; then
        COMPREPLY=($(compgen -W "rollback" -- "$cur")
            $(compgen -f -- "$cur"))
    else
        COMPREPLY=($(compgen -f -- "$cur"))
    fi
}
complete -F _ferm ferm

_import_ferm() {
    local cur
    cur=${COMP_WORDS[COMP_CWORD]}
    if [[ $cur == -* ]]; then
        COMPREPLY=($(compgen -W "@IMPORT_FERM_FLAGS@" -- "$cur"))
    else
        COMPREPLY=($(compgen -f -- "$cur"))
    fi
}
complete -F _import_ferm import-ferm
"""


def _flags(table: tuple[cli_doc.OptionDoc, ...]) -> str:
    """Every completable spelling of a table, space-joined."""
    return " ".join(
        spelling
        for opt in table
        if not opt.positional
        for spelling in opt.spellings
    )


def _value_cases(parser: object, extra: dict[str, str]) -> str:
    """One case-arm per option with completable values."""
    values: dict[str, str] = {}
    for action in parser._actions:  # type: ignore[attr-defined]  # noqa: SLF001
        if action.choices:
            joined = " ".join(str(choice) for choice in action.choices)
            for spelling in action.option_strings:
                values[spelling] = joined
    values.update(extra)
    return "\n".join(
        f'        {flag}) COMPREPLY=($(compgen -W "{words}"'
        f' -- "$cur")); return ;;'
        for flag, words in sorted(values.items())
    )


def generate() -> str:
    """Render the completion script text (deterministic)."""
    return (
        _TEMPLATE.replace("@MAIN_FLAGS@", _flags(cli_doc.FERM_OPTIONS))
        .replace("@ROLLBACK_FLAGS@", _flags(cli_doc.ROLLBACK_OPTIONS))
        .replace(
            "@MAIN_CASES@",
            _value_cases(_build_parser(), {"--domain": _DOMAIN_VALUES}),
        )
        .replace(
            "@ROLLBACK_CASES@",
            _value_cases(
                _build_rollback_parser(), {"--domain": _DOMAIN_VALUES}
            ),
        )
        .replace("@IMPORT_FERM_FLAGS@", _flags(cli_doc.IMPORT_FERM_OPTIONS))
    )


def main() -> int:
    """Regenerate the committed completion script in place."""
    _OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    _OUTPUT.write_text(generate(), encoding="utf-8")
    sys.stdout.write(f"generated {_OUTPUT}\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
