"""Unit tests for :mod:`pyferm.import_ferm`.

Covers the pure helpers (``ferm_escape``, ``format_array``, the tokenizer and
the ``Data::Dumper``-equivalent ``_canon``), the two-pass ``optimize`` merge
(common-prefix block and array combine), and an end-to-end ``Importer.run``
over a small ``iptables-save`` snippet.
"""

from __future__ import annotations

import io
import subprocess

import pytest

from pyferm.errors import FermError
from pyferm.import_ferm import (
    Importer,
    MatchEntry,
    Rule,
    _canon,
    _iptables_save_lines,
    _optimize,
    _tokenize,
    ferm_escape,
    format_array,
    main,
)
from pyferm.values import Multi, Negated


def _imported(save: str) -> str:
    """Run the importer over ``save`` and return its ferm output."""
    out = io.StringIO()
    Importer(out).run(save.splitlines())
    return out.getvalue()


def test_main_warns_and_continues_on_missing_file(
    capsys: pytest.CaptureFixture[str],
) -> None:
    # Perl reads inputs through the <> operator: an unopenable file
    # yields a "Can't open ..." warning on stderr and the run continues
    # (header printed, exit 0).
    assert main(["/nonexistent/ferm-no-such-save"]) == 0
    captured = capsys.readouterr()
    assert (
        "Can't open /nonexistent/ferm-no-such-save: "
        "No such file or directory" in captured.err
    )
    assert "# ferm rules generated by import-ferm" in captured.out


def test_ferm_escape_passes_bare_words() -> None:
    assert ferm_escape("eth0") == "eth0"
    assert ferm_escape("192.168.0.0/24") == "192.168.0.0/24"
    assert ferm_escape("a-b.c:d/e") == "a-b.c:d/e"


def test_ferm_escape_quotes_specials_and_empty() -> None:
    assert ferm_escape("a b") == "'a b'"
    assert ferm_escape("") == "''"
    assert ferm_escape("a,b") == "'a,b'"


def test_format_array_scalar_single_and_multi() -> None:
    assert format_array("x") == "x"
    assert format_array(["only"]) == "only"
    assert format_array(["a", "b", "c"]) == "(a b c)"
    # A blessed ``multi`` is dereferenced like a plain array.
    assert format_array(Multi(["a", "b"])) == "(a b)"


def test_tokenize_quotes_bang_and_words() -> None:
    assert _tokenize("--source 1.2.3.4 --jump ACCEPT") == [
        "--source",
        "1.2.3.4",
        "--jump",
        "ACCEPT",
    ]
    # A lone ``!`` splits even when glued to the next token.
    assert _tokenize("! --proto tcp") == ["!", "--proto", "tcp"]
    assert _tokenize('--comment "a b c"') == ["--comment", "a b c"]


def test_canon_distinguishes_negation_tag() -> None:
    # A negated value differs from the bare scalar and from a plain array.
    assert _canon(Negated("x")) != _canon("x")
    assert _canon(Negated("x")) != _canon(["x"])
    assert _canon(Negated("x")) == _canon(Negated("x"))


def test_optimize_factors_common_prefix_block() -> None:
    # Two rules sharing a leading match collapse into one block.
    rules = [
        Rule(
            match=[MatchEntry("proto", "tcp"), MatchEntry("saddr", "1")],
            jump="ACCEPT",
        ),
        Rule(
            match=[MatchEntry("proto", "tcp"), MatchEntry("saddr", "2")],
            jump="DROP",
        ),
    ]
    result = _optimize(rules)
    assert len(result) == 1
    block = result[0]
    assert block.block is not None
    assert [e.name for e in block.match] == ["proto"]
    assert len(block.block) == 2


def test_optimize_combines_array_values() -> None:
    # Two rules differing only in one scalar merge into an array value.
    rules = [
        Rule(match=[MatchEntry("saddr", "1.2.3.4")], jump="ACCEPT"),
        Rule(match=[MatchEntry("saddr", "5.6.7.8")], jump="ACCEPT"),
    ]
    result = _optimize(rules)
    assert len(result) == 1
    assert result[0].match[0].value == ["1.2.3.4", "5.6.7.8"]


def test_optimize_keeps_negated_rules_separate() -> None:
    # Negated values are not array-merging members, so they stay distinct.
    rules = [
        Rule(match=[MatchEntry("saddr", Negated("1.2.3.4"))], jump="DROP"),
        Rule(match=[MatchEntry("saddr", Negated("5.6.7.8"))], jump="DROP"),
    ]
    result = _optimize(rules)
    assert len(result) == 2


def test_run_emits_nested_blocks_and_policy() -> None:
    save = """\
# Generated by iptables-save
*filter
:INPUT ACCEPT [0:0]
-A INPUT --in-interface eth0 --jump ACCEPT
COMMIT
"""
    output = _imported(save)
    assert "domain ip {" in output
    assert "table filter {" in output
    assert "chain INPUT {" in output
    assert "policy ACCEPT;" in output
    assert "interface eth0 ACCEPT;" in output
    # Balanced braces: three opens (domain/table/chain) and three closes.
    assert output.count("{") == 3
    assert output.count("}") == 3


def test_run_negated_option_renders_bang_after_key() -> None:
    save = """\
*filter
:INPUT ACCEPT [0:0]
-A INPUT ! --source 10.0.0.0/8 --jump DROP
COMMIT
"""
    output = _imported(save)
    assert "saddr ! 10.0.0.0/8 DROP;" in output


def test_run_ported_protocol_enables_port_options() -> None:
    # sport/dport are not global options: a ported protocol (Perl :420)
    # brings both into scope, mirroring iptables' own -p tcp --dport.
    save = """\
*filter
:INPUT ACCEPT [0:0]
-A INPUT -p tcp --sport 1024 --dport 22 --jump ACCEPT
COMMIT
"""
    output = _imported(save)
    assert "protocol tcp sport 1024 dport 22 ACCEPT;" in output


def test_run_dport_without_ported_protocol_is_fatal() -> None:
    # Without a port-carrying protocol the option stays unknown, exactly
    # like iptables itself rejects a bare --dport.
    save = """\
*filter
:INPUT ACCEPT [0:0]
-A INPUT --dport 22 --jump ACCEPT
COMMIT
"""
    with pytest.raises(
        FermError, match="option 'dport' in line 3 not understood"
    ):
        _imported(save)


def test_run_negated_port_accepts_both_iptables_spellings() -> None:
    # Real iptables-save writes negation before the option ("! --dport"),
    # older dumps wrote it inline ("--dport ! 22"); ferm has only one
    # spelling, after the keyword.  Both inputs must converge on it.
    save = """\
*filter
:INPUT ACCEPT [0:0]
-A INPUT -p tcp ! --dport 22 -j DROP
-A INPUT -p tcp --sport ! 1024 -j ACCEPT
COMMIT
"""
    output = _imported(save)
    # The shared "protocol tcp" prefix is factored into a block, so the
    # negated rules sit on their own lines inside it.
    assert "protocol tcp {" in output
    assert "dport ! 22 DROP;" in output
    assert "sport ! 1024 ACCEPT;" in output


def test_run_skips_module_already_named_by_protocol() -> None:
    # iptables-save always spells "-p tcp -m tcp ..." even though the
    # module adds nothing; ferm's "protocol tcp" already loads it, so a
    # literal translation would emit a redundant "mod tcp" (Perl :433).
    save = """\
*filter
:INPUT ACCEPT [0:0]
-A INPUT -p tcp -m tcp --dport 22 --jump ACCEPT
COMMIT
"""
    output = _imported(save)
    assert "protocol tcp dport 22 ACCEPT;" in output
    assert "mod tcp" not in output


def test_run_match_module_enables_keywords_and_splits_csv() -> None:
    # "-m state" must pull the module's keyword table into scope (else
    # --state is "not understood") and a "=c" option splits its
    # comma-separated value into a ferm array.
    save = """\
*filter
:INPUT ACCEPT [0:0]
-A INPUT -m state --state RELATED,ESTABLISHED --jump ACCEPT
COMMIT
"""
    output = _imported(save)
    assert "mod state state (RELATED ESTABLISHED) ACCEPT;" in output


def test_run_multiport_dports_alias_expands_to_array() -> None:
    # multiport's --dports is an import-ferm alias for destination-ports,
    # and its comma list (a coderef param in Perl, ParamFunction here)
    # becomes a ferm array.
    save = """\
*filter
:INPUT ACCEPT [0:0]
-A INPUT -p tcp -m multiport --dports 22,80,443 --jump ACCEPT
COMMIT
"""
    output = _imported(save)
    assert (
        "protocol tcp mod multiport destination-ports (22 80 443) ACCEPT;"
        in output
    )


def test_run_quotes_match_and_target_values_with_spaces() -> None:
    # Quoted save-file values must survive as quoted ferm strings -- on
    # both sides of the jump: --comment is a match option, --log-prefix
    # belongs to the LOG target (parsed after the target swap, Perl :475).
    # The trailing space in "ferm: " is part of the prefix and must stay.
    save = """\
*filter
:INPUT ACCEPT [0:0]
-A INPUT -m comment --comment "allow ssh" -j LOG --log-prefix "ferm: "
COMMIT
"""
    output = _imported(save)
    assert "mod comment comment 'allow ssh' LOG log-prefix 'ferm: ';" in output


def test_run_save_header_selects_ip6_domain() -> None:
    # A real dump starts with "# Generated by ip6tables-save ...": the
    # header comment is the only thing that tells the importer to open
    # "domain ip6" instead of the default ip (Perl :513).
    save = """\
# Generated by ip6tables-save v1.8.9 on Thu Jun 11 10:00:00 2026
*filter
:INPUT ACCEPT [0:0]
-A INPUT -p tcp --dport 22 --jump ACCEPT
COMMIT
"""
    output = _imported(save)
    assert "domain ip6 {" in output
    assert "domain ip {" not in output


def test_run_emits_leftover_policy_of_chain_without_rules() -> None:
    # A declared chain that never receives an -A line still must keep its
    # policy: it is emitted as a one-line chain at the end of the table.
    save = """\
*filter
:INPUT ACCEPT [0:0]
:FORWARD DROP [0:0]
-A INPUT --jump ACCEPT
COMMIT
"""
    output = _imported(save)
    assert "chain FORWARD policy DROP;" in output


def test_iptables_save_lines_returns_stdout_lines(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    completed = subprocess.CompletedProcess(
        ["iptables-save"], 0, stdout="*filter\nCOMMIT\n"
    )
    commands: list[object] = []

    def fake_run(
        command: list[str], **_kwargs: object
    ) -> subprocess.CompletedProcess[str]:
        commands.append(command)
        return completed

    monkeypatch.setattr("pyferm.import_ferm.subprocess.run", fake_run)
    assert _iptables_save_lines() == ["*filter", "COMMIT"]
    # The dump must come from iptables-save itself (Perl :502).
    assert commands == [["iptables-save"]]


def test_iptables_save_lines_failure_is_ferm_error(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    # A missing/failing iptables-save must surface as a FermError (one
    # diagnostic line, exit 1) -- never as a raw traceback.
    def fail(*_args: object, **_kwargs: object) -> object:
        raise OSError(2, "No such file or directory")

    monkeypatch.setattr("pyferm.import_ferm.subprocess.run", fail)
    with pytest.raises(FermError, match="Failed to run iptables-save"):
        _iptables_save_lines()


def test_main_unknown_option_prints_usage_to_stderr(
    capsys: pytest.CaptureFixture[str],
) -> None:
    assert main(["-x"]) == 1
    captured = capsys.readouterr()
    assert "Usage:" in captured.err
    assert captured.out == ""
