"""
Mutation-kill coverage for :mod:`pyferm.import_ferm` survivors.

Each test pins a single behaviour that a surviving mutant would break: the
``_flush_domain`` chain-close emitter (reached only when a chain is left open
at end of input), the ``run`` line trimmer's exact strip set, and the
unknown-token warning's interpolated content.  The remaining survivors are
provably equivalent (dead ``.get("ip", {})`` defaults, boolean-context
``False``/``None`` swaps, a self-restoring ``_optimize`` guard, and the dead
``icmp6`` remap key) and carry no test here.
"""

from __future__ import annotations

import io
from typing import TYPE_CHECKING

from pyferm.import_ferm import Importer

if TYPE_CHECKING:
    import pytest


def _imported(lines: list[str]) -> str:
    """Run the importer over ``lines`` and return its ferm output."""
    out = io.StringIO()
    Importer(out).run(lines)
    return out.getvalue()


# --- _flush_domain: the chain-close brace (open chain at end of input) ------
#
# Every existing fixture ends its chains with COMMIT, so ``_flush_domain``'s
# ``if self.chain is not None`` branch (its first ``write_line("}")``) is only
# reached when the dump omits COMMIT and the chain is still open at EOF.  A
# mutant nulling that argument (``write_line(None)``) crashes, and one
# corrupting the brace (``"XX}XX"``) emits a bogus token and skips the indent
# dedent -- both caught by pinning the byte-exact close here.


_EXPECT_OPEN_CHAIN = (
    "# ferm rules generated by import-ferm\n"
    "# http://ferm.foo-projects.org/\n"
    "domain ip {\n"
    "    table filter {\n"
    "        chain INPUT {\n"
    "            policy ACCEPT;\n"
    "            ACCEPT;\n"
    "        }\n"
    "    }\n"
    "}\n"
)


def test_flush_domain_closes_open_chain_without_commit() -> None:
    """A COMMIT-less dump still closes its open chain, table and domain."""
    save = ["*filter", ":INPUT ACCEPT [0:0]", "-A INPUT -j ACCEPT"]
    assert _imported(save) == _EXPECT_OPEN_CHAIN


# --- run: the trailing strip set is exactly \r and \n -----------------------


def test_run_rstrip_set_excludes_ordinary_characters() -> None:
    """The line trimmer strips only CR/LF, never a trailing content byte."""
    # A table name ending in "X" must survive verbatim; widening the strip
    # set to include "X" would silently rename the table to "foo".
    output = _imported(["*fooX", "COMMIT"])
    assert "table fooX {" in output
    assert "table foo {" not in output


# --- _handle_rule: the unknown-token warning names the token ----------------


def test_handle_rule_unknown_token_warning_names_the_token(
    capsys: pytest.CaptureFixture[str],
) -> None:
    """An unrecognised bare token warns with its own text, not a null."""
    save = [
        "*filter",
        ":INPUT ACCEPT [0:0]",
        "-A INPUT bogusword -j ACCEPT",
        "COMMIT",
    ]
    _imported(save)
    assert "unknown token 'bogusword' in line 3" in capsys.readouterr().err
