"""Unit tests for :mod:`pyferm.domains`.

Covers the domain layer ported from ``reference/src/ferm`` (``:881-974``):
``find_tool`` in test mode and its ``*-legacy`` preference (incl. the
``--nolegacy`` deviation), the ``read_previous`` save parser, and
``initialize_domain``'s validation/idempotency/``capture_previous`` contract.
The mock-previous and ``eb`` atomic-save paths now belong to the backend
(:meth:`pyferm.backend.base.Backend.capture_previous`) and are covered in
``test_backend_iptables.py``.  The ``--shell`` snapshot likewise moved to the
backend (:meth:`pyferm.backend.base.Backend.shell_snapshot`, finding C2);
its tests live in ``test_backend_iptables.py`` (x_tables) and
``test_backend_nft.py`` (nft).
"""

from __future__ import annotations

import pytest

from pyferm.config import Options
from pyferm.domains import (
    DomainInfo,
    find_tool,
    initialize_domain,
    is_ip_family,
    parse_family,
    read_previous,
)
from pyferm.errors import FermError


@pytest.mark.parametrize("name", ["ip", "ip6", "arp", "eb"])
def test_parse_family_accepts_known(name: str) -> None:
    assert parse_family(name) == name


@pytest.mark.parametrize("bad", ["", "ipv4", "IP", "ip ", "tcp", "ip6 "])
def test_parse_family_rejects_unknown(bad: str) -> None:
    with pytest.raises(FermError):
        parse_family(bad)


def test_parse_family_idempotent() -> None:
    assert parse_family(parse_family("ip6")) == "ip6"


def test_is_ip_family_only_ip_and_ip6() -> None:
    assert is_ip_family("ip") is True
    assert is_ip_family("ip6") is True
    assert is_ip_family("arp") is False
    assert is_ip_family("eb") is False


# --- find_tool -------------------------------------------------------------


def test_find_tool_test_mode_returns_bare_name() -> None:
    # the reason golden output is path-independent (:883)
    assert find_tool("iptables-save", Options(test=True)) == "iptables-save"


def test_find_tool_prefers_legacy(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("PATH", "/bin")
    executable = {"/usr/sbin/iptables-legacy-save", "/usr/sbin/iptables-save"}

    def fake_access(path: str, _mode: int) -> bool:
        return path in executable

    monkeypatch.setattr("pyferm.domains.os.access", fake_access)
    # both exist, but the legacy spelling wins
    assert find_tool("iptables-save", Options()) == (
        "/usr/sbin/iptables-legacy-save"
    )


def test_find_tool_nolegacy_skips_legacy(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setenv("PATH", "/bin")
    executable = {"/usr/sbin/iptables-legacy-save", "/usr/sbin/iptables-save"}
    monkeypatch.setattr(
        "pyferm.domains.os.access", lambda p, _m: p in executable
    )
    # nolegacy: the legacy preference is bypassed, plain name resolves
    assert find_tool("iptables-save", Options(nolegacy=True)) == (
        "/usr/sbin/iptables-save"
    )


def test_find_tool_falls_back_to_plain_name(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setenv("PATH", "/bin")
    # only the non-legacy name exists
    monkeypatch.setattr(
        "pyferm.domains.os.access",
        lambda p, _m: p == "/sbin/iptables-save",
    )
    assert find_tool("iptables-save", Options()) == "/sbin/iptables-save"


def test_find_tool_not_found_raises(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("PATH", "")
    monkeypatch.setattr("pyferm.domains.os.access", lambda _p, _m: False)
    with pytest.raises(FermError, match="not found in PATH"):
        find_tool("nosuchtool", Options())


# --- read_previous ---------------------------------------------------------


def test_read_previous_records_tables_and_builtin_chains() -> None:
    dump = [
        "# Generated by iptables-save\n",
        "*filter\n",
        ":INPUT ACCEPT [0:0]\n",
        ":mychain - [0:0]\n",  # policy '-' -> not a builtin
        "-A INPUT -j ACCEPT\n",
        "COMMIT\n",
    ]
    info = DomainInfo()
    save = read_previous(dump, info)

    # text is returned verbatim for rollback
    assert save == "".join(dump)
    filter_table = info.tables["filter"]
    assert filter_table.has_builtin is True
    assert filter_table.chains["INPUT"].builtin is True
    # the '-' policy chain is not flagged builtin (and is never recorded here)
    assert "mychain" not in filter_table.chains


def test_read_previous_chain_before_table_is_ignored() -> None:
    # a chain line with no preceding *table has no table_info -> skipped
    info = DomainInfo()
    read_previous([":INPUT ACCEPT [0:0]\n"], info)
    assert info.tables == {}


# --- initialize_domain -----------------------------------------------------


def test_initialize_domain_invokes_capture_previous_after_tools() -> None:
    seen: list[tuple[str, dict[str, str]]] = []
    domains: dict[str, DomainInfo] = {}

    def capture(domain: str, info: DomainInfo) -> None:
        # the call invariant: tools are resolved BEFORE the capture
        seen.append((domain, dict(info.tools)))

    initialize_domain(
        "ip", domains, Options(test=True), capture_previous=capture
    )

    assert seen == [
        (
            "ip",
            {
                "tables": "iptables",
                "tables-save": "iptables-save",
                "tables-restore": "iptables-restore",
            },
        )
    ]


def test_initialize_domain_without_capture_previous_skips_capture() -> None:
    # the None seam is a unit-test/fuzz convenience: no previous state
    domains: dict[str, DomainInfo] = {}
    initialize_domain("ip", domains, Options(test=True))
    assert domains["ip"].previous is None
    assert domains["ip"].initialized is True


def test_initialize_domain_rejects_invalid_family() -> None:
    with pytest.raises(FermError, match="Invalid domain 'wat'"):
        initialize_domain("wat", {}, Options(test=True))


def test_initialize_domain_test_mode_tools_are_bare_names() -> None:
    domains: dict[str, DomainInfo] = {}
    initialize_domain("ip", domains, Options(test=True))
    info = domains["ip"]
    assert info.initialized is True
    # ip/ip6 get the save+restore tools; bare names under --test
    assert info.tools == {
        "tables": "iptables",
        "tables-save": "iptables-save",
        "tables-restore": "iptables-restore",
    }


def test_initialize_domain_arp_has_only_tables_tool() -> None:
    domains: dict[str, DomainInfo] = {}
    initialize_domain("arp", domains, Options(test=True))
    assert domains["arp"].tools == {"tables": "arptables"}


def test_initialize_domain_is_idempotent() -> None:
    domains: dict[str, DomainInfo] = {}
    initialize_domain("ip", domains, Options(test=True))
    domains["ip"].tools = {"sentinel": "kept"}  # would be clobbered on re-init
    initialize_domain("ip", domains, Options(test=True))
    assert domains["ip"].tools == {"sentinel": "kept"}


# --- initialize_domain: resolve_tools seam ---------------------------------


def test_initialize_domain_resolves_via_backend_tool_names() -> None:
    from pyferm.backend.iptables import IptablesBackend

    domains: dict[str, DomainInfo] = {}
    options = Options(test=True)
    initialize_domain(
        "ip", domains, options, resolve_tools=IptablesBackend().tool_names
    )
    assert domains["ip"].tools == {
        "tables": "iptables",
        "tables-save": "iptables-save",
        "tables-restore": "iptables-restore",
    }


def test_initialize_domain_resolves_single_nft_binary() -> None:
    domains: dict[str, DomainInfo] = {}
    initialize_domain(
        "ip",
        domains,
        Options(test=True),
        resolve_tools=lambda _domain: {"nft": "nft"},
    )
    assert domains["ip"].tools == {"nft": "nft"}
