"""Unit tests for :mod:`pyferm.import_ferm`.

Covers the pure helpers (``ferm_escape``, ``format_array``, the tokenizer),
the structural rule equality feeding the merge tests, the two-pass
``optimize`` merge (common-prefix block and array combine), and an
end-to-end ``Importer.run`` over a small ``iptables-save`` snippet.
"""

from __future__ import annotations

import io
import subprocess
from typing import TYPE_CHECKING

import pytest

if TYPE_CHECKING:
    from pathlib import Path

from pyferm.errors import FermError
from pyferm.import_ferm import (
    Importer,
    MatchEntry,
    Rule,
    _array_matches,
    _gather_input,
    _iptables_save_lines,
    _optimize,
    _prefix_matches,
    _tokenize,
    ferm_escape,
    format_array,
    main,
)
from pyferm.modules import Keyword
from pyferm.values import Multi, Negated, Params, PreNegated


def _imported(save: str) -> str:
    """Run the importer over ``save`` and return its ferm output."""
    out = io.StringIO()
    Importer(out).run(save.splitlines())
    return out.getvalue()


def test_main_warns_and_continues_on_missing_file(
    capsys: pytest.CaptureFixture[str],
) -> None:
    # Perl reads inputs through the <> operator: an unopenable file
    # yields a "Can't open ..." warning on stderr and the run continues
    # (header printed, exit 0).
    assert main(["/nonexistent/ferm-no-such-save"]) == 0
    captured = capsys.readouterr()
    assert (
        "Can't open /nonexistent/ferm-no-such-save: "
        "No such file or directory" in captured.err
    )
    assert "# ferm rules generated by import-ferm" in captured.out


def test_ferm_escape_passes_bare_words() -> None:
    assert ferm_escape("eth0") == "eth0"
    assert ferm_escape("192.168.0.0/24") == "192.168.0.0/24"
    assert ferm_escape("a-b.c:d/e") == "a-b.c:d/e"


def test_ferm_escape_quotes_specials_and_empty() -> None:
    assert ferm_escape("a b") == "'a b'"
    assert ferm_escape("") == "''"
    assert ferm_escape("a,b") == "'a,b'"


def test_format_array_scalar_single_and_multi() -> None:
    assert format_array("x") == "x"
    assert format_array(["only"]) == "only"
    assert format_array(["a", "b", "c"]) == "(a b c)"
    # A blessed ``multi`` is dereferenced like a plain array.
    assert format_array(Multi(["a", "b"])) == "(a b)"


def test_tokenize_quotes_bang_and_words() -> None:
    assert _tokenize("--source 1.2.3.4 --jump ACCEPT") == [
        "--source",
        "1.2.3.4",
        "--jump",
        "ACCEPT",
    ]
    # A lone ``!`` splits even when glued to the next token.
    assert _tokenize("! --proto tcp") == ["!", "--proto", "tcp"]
    assert _tokenize('--comment "a b c"') == ["--comment", "a b c"]


def test_rule_equality_distinguishes_negation_tag() -> None:
    # A negated value differs from the bare scalar and from a plain array:
    # the frozen value dataclasses require the class to match (the Perl
    # Dumper blessed tag), so negated options never merge with plain ones.
    assert MatchEntry("s", Negated("x")) != MatchEntry("s", "x")
    assert MatchEntry("s", Negated("x")) != MatchEntry("s", ["x"])
    assert MatchEntry("s", Negated("x")) == MatchEntry("s", Negated("x"))


def test_rule_equality_preserves_collection_element_content() -> None:
    # Two values differing only in an element must compare unequal;
    # collapsing the element would let _optimize merge genuinely distinct
    # rules.
    assert MatchEntry("s", ["a"]) != MatchEntry("s", ["b"])
    assert MatchEntry("s", Multi(["a"])) != MatchEntry("s", Multi(["b"]))
    assert MatchEntry("s", PreNegated("a")) != MatchEntry("s", PreNegated("b"))
    assert MatchEntry("s", Params(["a"])) != MatchEntry("s", Params(["b"]))
    assert Keyword("x", "1") != Keyword("x", "2")


def test_rule_equality_covers_optional_fields() -> None:
    # Optional rule fields feed the merge-equality test (_array_matches);
    # two rules differing only in one such field must not compare equal.
    assert Rule(target=[MatchEntry("-j", "A")]) != Rule(
        target=[MatchEntry("-j", "B")]
    )
    assert Rule(jump="A") != Rule(jump="B")
    assert Rule(goto="A") != Rule(goto="B")
    assert Rule(match_keywords={"x": Keyword("x", "1")}) != Rule(
        match_keywords={"x": Keyword("x", "2")}
    )
    assert Rule(block=[Rule(jump="A")]) != Rule(block=[Rule(jump="B")])
    assert Rule(match=[MatchEntry("saddr", "1")]) != Rule(
        match=[MatchEntry("saddr", "2")]
    )


def test_rule_equality_ignores_cur() -> None:
    # cur is transient parse state, always None again by optimize time; it
    # is excluded from comparison (compare=False) so a stray alias could
    # never block a merge.
    entry = MatchEntry("proto", "tcp")
    aliased = Rule(match=[entry])
    aliased.cur = aliased.match
    assert aliased == Rule(match=[MatchEntry("proto", "tcp")])


def test_prefix_matches_requires_other_match() -> None:
    # A bare "-A INPUT -j ACCEPT" parses to match=[]; the bool(other.match)
    # guard must reject it instead of raising IndexError.
    prefix = Rule(match=[MatchEntry("proto", "tcp")])
    assert not _prefix_matches(prefix, Rule())


def test_array_matches_leaves_operands_intact() -> None:
    # The tail comparison works on ephemeral shallow copies; the operands
    # must keep their full match lists for the later merge passes.
    rule1 = Rule(match=[MatchEntry("saddr", "1"), MatchEntry("proto", "tcp")])
    rule2 = Rule(match=[MatchEntry("saddr", "2"), MatchEntry("proto", "tcp")])
    assert _array_matches(rule1, rule2)
    assert [entry.name for entry in rule1.match] == ["saddr", "proto"]
    assert [entry.name for entry in rule2.match] == ["saddr", "proto"]


def test_optimize_factors_common_prefix_block() -> None:
    # Two rules sharing a leading match collapse into one block.
    rules = [
        Rule(
            match=[MatchEntry("proto", "tcp"), MatchEntry("saddr", "1")],
            jump="ACCEPT",
        ),
        Rule(
            match=[MatchEntry("proto", "tcp"), MatchEntry("saddr", "2")],
            jump="DROP",
        ),
    ]
    result = _optimize(rules)
    assert len(result) == 1
    block = result[0]
    assert block.block is not None
    assert [e.name for e in block.match] == ["proto"]
    assert len(block.block) == 2


def test_optimize_combines_array_values() -> None:
    # Two rules differing only in one scalar merge into an array value.
    rules = [
        Rule(match=[MatchEntry("saddr", "1.2.3.4")], jump="ACCEPT"),
        Rule(match=[MatchEntry("saddr", "5.6.7.8")], jump="ACCEPT"),
    ]
    result = _optimize(rules)
    assert len(result) == 1
    assert result[0].match[0].value == ["1.2.3.4", "5.6.7.8"]


def test_optimize_flattens_existing_array_member() -> None:
    # When a merging member already holds a list value, its elements are
    # spliced into the combined array (extend), not nested as one element.
    rules = [
        Rule(
            match=[MatchEntry("saddr", ["1.1.1.1", "2.2.2.2"])], jump="ACCEPT"
        ),
        Rule(match=[MatchEntry("saddr", "3.3.3.3")], jump="ACCEPT"),
    ]
    result = _optimize(rules)
    assert len(result) == 1
    assert result[0].match[0].value == ["1.1.1.1", "2.2.2.2", "3.3.3.3"]


def test_run_shared_prefix_collapsing_to_one_array_reinserts_match() -> None:
    # Two rules share "protocol tcp" and differ only in saddr: the extracted
    # block optimizes down to a single array-valued rule, so the shared match
    # is re-inserted at its front rather than wrapped in a nested block.
    save = """\
*filter
:INPUT ACCEPT [0:0]
-A INPUT -p tcp -s 1.1.1.1 -j ACCEPT
-A INPUT -p tcp -s 2.2.2.2 -j ACCEPT
COMMIT
"""
    output = _imported(save)
    assert "protocol tcp saddr (1.1.1.1 2.2.2.2) ACCEPT;" in output


def test_run_string_param_option_stays_unmerged() -> None:
    # "comment" takes a single string (=s): two rules differing only in the
    # comment value must NOT array-merge into "comment (aaa bbb)"; the =s guard
    # in _array_match_count keeps them on separate lines.  This also pins that
    # a jump populates rule.match_keywords (else the guard cannot see params).
    save = """\
*filter
:INPUT ACCEPT [0:0]
-A INPUT -m comment --comment aaa -j ACCEPT
-A INPUT -m comment --comment bbb -j ACCEPT
COMMIT
"""
    output = _imported(save)
    assert "comment aaa ACCEPT;" in output
    assert "comment bbb ACCEPT;" in output
    assert "(aaa bbb)" not in output


def test_optimize_combines_three_or_more_values() -> None:
    # The array combine folds every consecutive match, not just the first
    # following one: three rules collapse into a single three-element array.
    rules = [
        Rule(match=[MatchEntry("saddr", "1.1.1.1")], jump="ACCEPT"),
        Rule(match=[MatchEntry("saddr", "2.2.2.2")], jump="ACCEPT"),
        Rule(match=[MatchEntry("saddr", "3.3.3.3")], jump="ACCEPT"),
    ]
    result = _optimize(rules)
    assert len(result) == 1
    assert result[0].match[0].value == ["1.1.1.1", "2.2.2.2", "3.3.3.3"]


def test_run_comma_list_option_array_merges() -> None:
    # "state" takes a comma list (=c), not a single string (=s): two rules
    # differing only in the state value MUST array-merge -- the =s guard is
    # specific to "s" and must not fire for other string param codes.
    save = """\
*filter
:INPUT ACCEPT [0:0]
-A INPUT -m state --state NEW -j ACCEPT
-A INPUT -m state --state ESTABLISHED -j ACCEPT
COMMIT
"""
    output = _imported(save)
    assert "mod state state (NEW ESTABLISHED) ACCEPT;" in output


def test_optimize_keeps_negated_rules_separate() -> None:
    # Negated values are not array-merging members, so they stay distinct.
    rules = [
        Rule(match=[MatchEntry("saddr", Negated("1.2.3.4"))], jump="DROP"),
        Rule(match=[MatchEntry("saddr", Negated("5.6.7.8"))], jump="DROP"),
    ]
    result = _optimize(rules)
    assert len(result) == 2


def test_run_emits_nested_blocks_and_policy() -> None:
    save = """\
# Generated by iptables-save
*filter
:INPUT ACCEPT [0:0]
-A INPUT --in-interface eth0 --jump ACCEPT
COMMIT
"""
    output = _imported(save)
    assert "domain ip {" in output
    assert "table filter {" in output
    assert "chain INPUT {" in output
    assert "policy ACCEPT;" in output
    assert "interface eth0 ACCEPT;" in output
    # Balanced braces: three opens (domain/table/chain) and three closes.
    assert output.count("{") == 3
    assert output.count("}") == 3


def test_run_negated_option_renders_bang_after_key() -> None:
    save = """\
*filter
:INPUT ACCEPT [0:0]
-A INPUT ! --source 10.0.0.0/8 --jump DROP
COMMIT
"""
    output = _imported(save)
    assert "saddr ! 10.0.0.0/8 DROP;" in output


def test_run_ported_protocol_enables_port_options() -> None:
    # sport/dport are not global options: a ported protocol (Perl :420)
    # brings both into scope, mirroring iptables' own -p tcp --dport.
    save = """\
*filter
:INPUT ACCEPT [0:0]
-A INPUT -p tcp --sport 1024 --dport 22 --jump ACCEPT
COMMIT
"""
    output = _imported(save)
    assert "protocol tcp sport 1024 dport 22 ACCEPT;" in output


def test_run_dport_without_ported_protocol_is_fatal() -> None:
    # Without a port-carrying protocol the option stays unknown, exactly
    # like iptables itself rejects a bare --dport.
    save = """\
*filter
:INPUT ACCEPT [0:0]
-A INPUT --dport 22 --jump ACCEPT
COMMIT
"""
    with pytest.raises(
        FermError, match="option 'dport' in line 3 not understood"
    ):
        _imported(save)


# -- malformed save-file diagnostics ---------------------------------------
#
# The importer parses a trusted iptables-save dump, but a truncated or
# hand-edited one must abort with a located message rather than emit a
# silently wrong config.  These pin the rule-parser's error sinks.


def test_run_negated_non_negatable_option_is_fatal() -> None:
    # A leading "!" before a target makes no sense; jump is not negatable.
    save = """\
*filter
:INPUT ACCEPT [0:0]
-A INPUT ! --jump ACCEPT
COMMIT
"""
    with pytest.raises(
        FermError, match="option 'jump' in line 3 cannot be negated"
    ):
        _imported(save)


def test_run_bang_without_an_option_is_fatal() -> None:
    # "!" must be followed by an option token, not a bare word.
    save = """\
*filter
:INPUT ACCEPT [0:0]
-A INPUT ! bogus --jump ACCEPT
COMMIT
"""
    with pytest.raises(FermError, match="option expected in line 3"):
        _imported(save)


def test_run_jump_without_target_is_fatal() -> None:
    # A truncated rule ending at "--jump" has no target to consume.
    save = """\
*filter
:INPUT ACCEPT [0:0]
-A INPUT --jump
COMMIT
"""
    with pytest.raises(FermError, match="parse error in line 3"):
        _imported(save)


def test_run_negated_port_accepts_both_iptables_spellings() -> None:
    # Real iptables-save writes negation before the option ("! --dport"),
    # older dumps wrote it inline ("--dport ! 22"); ferm has only one
    # spelling, after the keyword.  Both inputs must converge on it.
    save = """\
*filter
:INPUT ACCEPT [0:0]
-A INPUT -p tcp ! --dport 22 -j DROP
-A INPUT -p tcp --sport ! 1024 -j ACCEPT
COMMIT
"""
    output = _imported(save)
    # The shared "protocol tcp" prefix is factored into a block, so the
    # negated rules sit on their own lines inside it.
    assert "protocol tcp {" in output
    assert "dport ! 22 DROP;" in output
    assert "sport ! 1024 ACCEPT;" in output


def test_run_skips_module_already_named_by_protocol() -> None:
    # iptables-save always spells "-p tcp -m tcp ..." even though the
    # module adds nothing; ferm's "protocol tcp" already loads it, so a
    # literal translation would emit a redundant "mod tcp" (Perl :433).
    save = """\
*filter
:INPUT ACCEPT [0:0]
-A INPUT -p tcp -m tcp --dport 22 --jump ACCEPT
COMMIT
"""
    output = _imported(save)
    assert "protocol tcp dport 22 ACCEPT;" in output
    assert "mod tcp" not in output


def test_run_match_module_enables_keywords_and_splits_csv() -> None:
    # "-m state" must pull the module's keyword table into scope (else
    # --state is "not understood") and a "=c" option splits its
    # comma-separated value into a ferm array.
    save = """\
*filter
:INPUT ACCEPT [0:0]
-A INPUT -m state --state RELATED,ESTABLISHED --jump ACCEPT
COMMIT
"""
    output = _imported(save)
    assert "mod state state (RELATED ESTABLISHED) ACCEPT;" in output


def test_run_multiport_dports_alias_expands_to_array() -> None:
    # multiport's --dports is an import-ferm alias for destination-ports,
    # and its comma list (a coderef param in Perl, ParamFunction here)
    # becomes a ferm array.
    save = """\
*filter
:INPUT ACCEPT [0:0]
-A INPUT -p tcp -m multiport --dports 22,80,443 --jump ACCEPT
COMMIT
"""
    output = _imported(save)
    assert (
        "protocol tcp mod multiport destination-ports (22 80 443) ACCEPT;"
        in output
    )


def test_run_quotes_match_and_target_values_with_spaces() -> None:
    # Quoted save-file values must survive as quoted ferm strings -- on
    # both sides of the jump: --comment is a match option, --log-prefix
    # belongs to the LOG target (parsed after the target swap, Perl :475).
    # The trailing space in "ferm: " is part of the prefix and must stay.
    save = """\
*filter
:INPUT ACCEPT [0:0]
-A INPUT -m comment --comment "allow ssh" -j LOG --log-prefix "ferm: "
COMMIT
"""
    output = _imported(save)
    assert "mod comment comment 'allow ssh' LOG log-prefix 'ferm: ';" in output


def test_run_save_header_selects_ip6_domain() -> None:
    # A real dump starts with "# Generated by ip6tables-save ...": the
    # header comment is the only thing that tells the importer to open
    # "domain ip6" instead of the default ip (Perl :513).
    save = """\
# Generated by ip6tables-save v1.8.9 on Thu Jun 11 10:00:00 2026
*filter
:INPUT ACCEPT [0:0]
-A INPUT -p tcp --dport 22 --jump ACCEPT
COMMIT
"""
    output = _imported(save)
    assert "domain ip6 {" in output
    assert "domain ip {" not in output


def test_run_emits_leftover_policy_of_chain_without_rules() -> None:
    # A declared chain that never receives an -A line still must keep its
    # policy: it is emitted as a one-line chain at the end of the table.
    save = """\
*filter
:INPUT ACCEPT [0:0]
:FORWARD DROP [0:0]
-A INPUT --jump ACCEPT
COMMIT
"""
    output = _imported(save)
    assert "chain FORWARD policy DROP;" in output


def test_iptables_save_lines_returns_stdout_lines(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    completed = subprocess.CompletedProcess(
        ["iptables-save"], 0, stdout="*filter\nCOMMIT\n"
    )
    commands: list[object] = []

    def fake_run(
        command: list[str], **_kwargs: object
    ) -> subprocess.CompletedProcess[str]:
        commands.append(command)
        return completed

    monkeypatch.setattr("pyferm.import_ferm.subprocess.run", fake_run)
    assert _iptables_save_lines() == ["*filter", "COMMIT"]
    # The dump must come from iptables-save itself (Perl :502).
    assert commands == [["iptables-save"]]


def test_iptables_save_lines_failure_is_ferm_error(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    # A missing/failing iptables-save must surface as a FermError (one
    # diagnostic line, exit 1) -- never as a raw traceback.
    def fail(*_args: object, **_kwargs: object) -> object:
        raise OSError(2, "No such file or directory")

    monkeypatch.setattr("pyferm.import_ferm.subprocess.run", fail)
    with pytest.raises(FermError, match="Failed to run iptables-save"):
        _iptables_save_lines()


def test_main_unknown_option_prints_usage_to_stderr(
    capsys: pytest.CaptureFixture[str],
) -> None:
    assert main(["-x"]) == 1
    captured = capsys.readouterr()
    assert "Usage:" in captured.err
    assert captured.out == ""


# --- _gather_input latin-1 file read ---------------------------------------


def test_gather_input_reads_high_bytes(tmp_path: Path) -> None:
    # latin-1 decode preserves byte 0xff as the single char U+00FF;
    # utf-8 would raise UnicodeDecodeError on that byte.
    save = tmp_path / "dump"
    save.write_bytes(b"# \xff\n*filter\nCOMMIT\n")
    lines = _gather_input([str(save)])
    # _gather_input uses splitlines(), so there are no trailing newlines
    assert lines[0] == "# \xff"


def test_run_consecutive_u32_options_merge_into_array() -> None:
    # Two consecutive ``--u32`` options on the same rule must fold into a
    # ferm array rather than being emitted as two separate u32 rules.
    # This exercises the Multi-merge path (import_ferm.py parse_option).
    save = """\
*filter
:INPUT ACCEPT [0:0]
-A INPUT -m u32 --u32 "0x0&0xF=0x5" --u32 "0x4&0xFFFF=0x3C" --jump ACCEPT
COMMIT
"""
    output = _imported(save)
    assert "u32 ('0x0&0xF=0x5' '0x4&0xFFFF=0x3C') ACCEPT;" in output


# --- NAT / mangle / user-chain coverage (F2 gap) --------------------------
#
# The cases below cover the import direction for table families and target
# types that are absent from the unit tests above: nat (DNAT/SNAT/MASQUERADE),
# mangle (MARK), and a user-defined chain with a jump to it.  All three were
# only reachable via the golden round-trip fixtures before this addition.


def test_run_nat_dnat_snat_masquerade() -> None:
    # *nat table: DNAT translates --to-destination to the "to" keyword;
    # SNAT translates --to-source likewise; MASQUERADE carries no extra
    # keyword but must appear after the translated match options.
    save = """\
# Generated by iptables-save
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
-A PREROUTING -p tcp -m tcp --dport 8080 -j DNAT --to-destination 192.0.2.10:80
-A POSTROUTING -s 10.0.0.0/8 -o eth0 -j MASQUERADE
-A POSTROUTING -s 10.1.0.0/16 -j SNAT --to-source 198.51.100.1
COMMIT
"""
    output = _imported(save)
    assert "table nat {" in output
    # --to-destination translates to the "to" keyword in ferm.
    assert "protocol tcp dport 8080 DNAT to 192.0.2.10:80;" in output
    # -o eth0 becomes "outerface eth0"; MASQUERADE has no extra keyword.
    assert "saddr 10.0.0.0/8 outerface eth0 MASQUERADE;" in output
    # --to-source translates to the "to" keyword under SNAT as well.
    assert "saddr 10.1.0.0/16 SNAT to 198.51.100.1;" in output


def test_run_mangle_mark_set_mark() -> None:
    # *mangle table: MARK --set-mark must translate to "MARK set-mark <hex>".
    # The hex value is preserved verbatim (not converted to decimal).
    save = """\
# Generated by iptables-save
*mangle
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
-A OUTPUT -p tcp -m tcp --dport 25 -j MARK --set-mark 0x2
COMMIT
"""
    output = _imported(save)
    assert "table mangle {" in output
    # The MARK target keyword and its set-mark parameter must survive intact.
    assert "protocol tcp dport 25 MARK set-mark 0x2;" in output


def test_run_user_defined_chain_and_jump_to_it() -> None:
    # A chain declared with "- [0:0]" (no policy) is a user-defined chain.
    # The importer must emit a forward declaration ("chain FOO;") before the
    # chains that reference it, and then a full block with its own rules;
    # the jump from a built-in chain must use the ferm "jump" keyword.
    save = """\
# Generated by iptables-save
*filter
:INPUT ACCEPT [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]
:LOGDROP - [0:0]
-A INPUT -j LOGDROP
-A LOGDROP -j LOG --log-prefix "dropped: "
-A LOGDROP -j DROP
COMMIT
"""
    output = _imported(save)
    # The user chain must appear as an empty forward declaration.
    assert "chain LOGDROP;" in output
    # The jump from INPUT must use the ferm "jump" keyword, not the chain name
    # as a target verb.
    assert "jump LOGDROP;" in output
    # The user chain must also have its own rule block.
    assert "chain LOGDROP {" in output
    # The LOG rule inside the user chain must carry the translated log-prefix.
    assert "LOG log-prefix 'dropped: ';" in output


# --- parse_option dispatch coverage ---------------------------------------
#
# The cases below pin the option-name resolution and per-branch keyword
# loading in ``Importer.parse_option`` that the round-trip fixtures exercise
# but the unit tests above did not: the sports alias, protocol/match keyword
# merges, negated protocol, goto, and the icmp6-under-ipv6-icmp coverage.


def test_run_multiport_sports_alias_expands_to_array() -> None:
    # multiport's --sports is the source-ports alias (mirror of --dports); its
    # comma list becomes a ferm array under the "source-ports" keyword.
    save = """\
*filter
:INPUT ACCEPT [0:0]
-A INPUT -p tcp -m multiport --sports 22,80 --jump ACCEPT
COMMIT
"""
    output = _imported(save)
    assert "protocol tcp mod multiport source-ports (22 80) ACCEPT;" in output


def test_run_protocol_merges_proto_specific_keywords() -> None:
    # "-p tcp" must load tcp's own keyword table (here --syn) via PROTO_DEFS,
    # not merely the port options; a broken lookup leaves --syn "not
    # understood".
    save = """\
*filter
:INPUT ACCEPT [0:0]
-A INPUT -p tcp --syn --jump ACCEPT
COMMIT
"""
    output = _imported(save)
    assert "protocol tcp syn ACCEPT;" in output


def test_run_match_module_falls_back_to_proto_keywords() -> None:
    # "-m tcp" names a protocol module that is absent from MATCH_DEFS, so the
    # importer falls back to PROTO_DEFS for tcp's keywords (--syn); tcp being a
    # port protocol also brings --dport into scope -- both without a "-p tcp".
    save = """\
*filter
:INPUT ACCEPT [0:0]
-A INPUT -m tcp --syn --dport 22 --jump ACCEPT
COMMIT
"""
    output = _imported(save)
    assert "mod tcp syn dport 22 ACCEPT;" in output


def test_run_negated_protocol_renders_bang() -> None:
    # A leading "!" before -p negates the protocol match; dropping the negation
    # flag would emit a plain "protocol tcp".
    save = """\
*filter
:INPUT ACCEPT [0:0]
-A INPUT ! -p tcp --jump ACCEPT
COMMIT
"""
    output = _imported(save)
    assert "protocol ! tcp ACCEPT;" in output


def test_run_goto_target_uses_goto_keyword() -> None:
    # "-g CHAIN" is a goto, distinct from "-j": it consumes the chain name and
    # renders "goto CHAIN;".
    save = """\
*filter
:INPUT ACCEPT [0:0]
:LOGC - [0:0]
-A INPUT -g LOGC
-A LOGC -j DROP
COMMIT
"""
    output = _imported(save)
    assert "goto LOGC;" in output


def test_run_multi_code_option_becomes_params() -> None:
    # tcp-flags takes two arguments (=cc): a comma-list mask and a comma-list
    # of set flags, emitted as two ferm arguments ("(SYN ACK) SYN").  This is
    # the multi-code branch that builds a Params of both parts.
    save = """\
*filter
:INPUT ACCEPT [0:0]
-A INPUT -p tcp --tcp-flags SYN,ACK SYN -j ACCEPT
COMMIT
"""
    output = _imported(save)
    assert "protocol tcp tcp-flags (SYN ACK) SYN ACCEPT;" in output


def test_run_pre_negated_option_keeps_its_value() -> None:
    # addrtype's src-type is a pre-negation keyword: "! --src-type LOCAL"
    # renders the "!" before the keyword and must keep its value ("LOCAL").
    save = """\
*filter
:INPUT ACCEPT [0:0]
-A INPUT -m addrtype ! --src-type LOCAL -j ACCEPT
COMMIT
"""
    output = _imported(save)
    assert "mod addrtype ! src-type LOCAL ACCEPT;" in output


def test_run_icmp6_module_covered_by_ipv6_icmp_protocol() -> None:
    # Under "-p ipv6-icmp" the "-m icmp6" module is already loaded, so no
    # redundant "mod" is emitted, and icmp6 is remapped to icmpv6 for the
    # keyword lookup (else --icmpv6-type would be "not understood").
    save = """\
# Generated by ip6tables-save
*filter
:INPUT ACCEPT [0:0]
-A INPUT -p ipv6-icmp -m icmp6 --icmpv6-type echo-request -j ACCEPT
COMMIT
"""
    output = _imported(save)
    assert "protocol ipv6-icmp icmpv6-type echo-request ACCEPT;" in output
    assert "mod icmp6" not in output


def test_run_icmpv6_protocol_spelling_covers_icmp6_module() -> None:
    # The alternate "-p icmpv6" spelling equally covers "-m icmp6": still no
    # redundant "mod" and the keyword table still loads.
    save = """\
# Generated by ip6tables-save
*filter
:INPUT ACCEPT [0:0]
-A INPUT -p icmpv6 -m icmp6 --icmpv6-type echo-request -j ACCEPT
COMMIT
"""
    output = _imported(save)
    assert "protocol icmpv6 icmpv6-type echo-request ACCEPT;" in output
    assert "mod icmp6" not in output
