"""SetRef expands to cartesian product under the iptables backend."""

from __future__ import annotations

import subprocess
import sys

import pytest

from pyferm.errors import FermError
from pyferm.parser import Parser
from pyferm.scope import Option, Rule
from pyferm.values import SetRef


def _run(
    src: str, extra_flags: list[str] | None = None
) -> subprocess.CompletedProcess[str]:
    """Run pyferm in --test --noexec --lines mode on *src* via stdin."""
    flags = extra_flags or []
    return subprocess.run(
        [
            sys.executable,
            "-m",
            "pyferm",
            "--test",
            "--noexec",
            "--lines",
            *flags,
            "-",
        ],
        input=src,
        capture_output=True,
        text=True,
        check=False,
    )


def _strip_generated_comment(text: str) -> str:
    """Remove the ``# Generated by ferm ...`` timestamp header line.

    The header embeds a wall-clock timestamp that differs between two
    back-to-back subprocess calls when they straddle a second boundary.
    Strip it before equality comparisons that care only about rules.
    """
    lines = text.splitlines(keepends=True)
    return "".join(
        line for line in lines if not line.startswith("# Generated by ferm")
    )


def test_setref_expands_like_literal_list() -> None:
    """A named set as a selector expands identically to a literal list."""
    with_set = _run(
        "@set $p = (22 80);\n"
        "domain ip table filter chain INPUT { proto tcp dport $p ACCEPT; }\n"
    )
    literal = _run(
        "domain ip table filter chain INPUT "
        "{ proto tcp dport (22 80) ACCEPT; }\n"
    )
    assert with_set.returncode == 0, f"set variant failed:\n{with_set.stderr}"
    assert literal.returncode == 0, (
        f"literal variant failed:\n{literal.stderr}"
    )
    assert _strip_generated_comment(
        with_set.stdout
    ) == _strip_generated_comment(literal.stdout), (
        "set variant output differs from literal:\n"
        f"--- set variant ---\n{with_set.stdout}"
        f"--- literal ---\n{literal.stdout}"
    )


def test_lone_parenthesised_set_ok() -> None:
    """Lone ``($p)`` is accepted and equals bare ``$p`` output."""
    with_parens = _run(
        "@set $p = (22 80);\n"
        "domain ip table filter chain INPUT "
        "{ proto tcp dport ($p) ACCEPT; }\n"
    )
    without_parens = _run(
        "@set $p = (22 80);\n"
        "domain ip table filter chain INPUT "
        "{ proto tcp dport $p ACCEPT; }\n"
    )
    assert with_parens.returncode == 0, (
        f"lone parenthesised set failed:\n{with_parens.stderr}"
    )
    assert without_parens.returncode == 0, (
        f"bare set failed:\n{without_parens.stderr}"
    )
    assert _strip_generated_comment(
        with_parens.stdout
    ) == _strip_generated_comment(without_parens.stdout), (
        "($p) and $p produce different output:\n"
        f"--- with parens ---\n{with_parens.stdout}"
        f"--- without parens ---\n{without_parens.stdout}"
    )


def test_mixed_literal_before_set_rejected() -> None:
    """Literal before a set in one selector is rejected at parse time."""
    proc = _run(
        "@set $p = (80);\n"
        "domain ip table filter chain INPUT "
        "{ proto tcp dport (22 $p) ACCEPT; }\n"
    )
    assert proc.returncode != 0, "expected rejection of mixed literal+set"
    assert "mixed with other values" in proc.stderr, (
        f"expected 'mixed with other values' in stderr, got:\n{proc.stderr}"
    )


def test_mixed_set_before_literal_rejected() -> None:
    """Set before a literal in one selector is rejected at parse time."""
    proc = _run(
        "@set $p = (80);\n"
        "domain ip table filter chain INPUT "
        "{ proto tcp dport ($p 22) ACCEPT; }\n"
    )
    assert proc.returncode != 0, "expected rejection of set+literal mix"
    assert "mixed with other values" in proc.stderr, (
        f"expected 'mixed with other values' in stderr, got:\n{proc.stderr}"
    )


def test_mixed_set_before_literal_rejected_under_nft() -> None:
    """The mixed-selector guard fires under --nft (backend-agnostic gate)."""
    proc = _run(
        "@set $p = (80);\n"
        "domain ip table filter chain INPUT "
        "{ proto tcp dport ($p 22) ACCEPT; }\n",
        extra_flags=["--nft"],
    )
    assert proc.returncode != 0, (
        "expected rejection of set+literal mix under --nft"
    )
    assert "mixed with other values" in proc.stderr, (
        f"expected 'mixed with other values' in stderr, got:\n{proc.stderr}"
    )


def test_mixed_literal_before_set_rejected_under_nft() -> None:
    """Literal before a named set in one selector is rejected at parse time.

    This covers the (22 $set) ordering under --nft (regression for the
    _REF_TYPES omission that let this slip past the parse-time guard).
    """
    proc = _run(
        "@set $p = (80);\n"
        "domain ip table filter chain INPUT "
        "{ proto tcp dport (22 $p) ACCEPT; }\n",
        extra_flags=["--nft"],
    )
    assert proc.returncode != 0, (
        "expected rejection of literal+set mix under --nft"
    )
    assert "mixed with other values" in proc.stderr, (
        f"expected 'mixed with other values' in stderr, got:\n{proc.stderr}"
    )


def test_nft_does_not_silently_expand_set() -> None:
    """Under --nft the nft backend renders SetRef as a @name reference.

    The iptables pre-pass (``_expand_setrefs_for_iptables``) is gated on
    ``not self.options.nft`` and does NOT run under ``--nft``.  Instead the
    nft backend translates the SetRef to a ``@name`` set reference rather
    than expanding it into concrete rules -- confirming the gate is real and
    the backends diverge intentionally here.
    """
    proc = _run(
        "@set $p = (22 80);\n"
        "domain ip table filter chain INPUT "
        "{ proto tcp dport $p ACCEPT; }\n",
        extra_flags=["--nft"],
    )
    assert proc.returncode == 0, (
        f"nft SetRef translation failed:\n{proc.stderr}"
    )
    assert "@p" in proc.stdout, (
        f"expected @p reference in nft output, got:\n{proc.stdout}"
    )
    # The iptables pre-pass would have produced separate concrete rules
    # (one per element); confirm neither element appears as a standalone rule.
    assert "dport 22" not in proc.stdout, (
        "iptables-style expansion must not appear in nft output"
    )
    assert "dport 80" not in proc.stdout, (
        "iptables-style expansion must not appear in nft output"
    )


# ---------------------------------------------------------------------------
# In-process unit mirrors for the parse-phase pre-pass.  The subprocess
# cases above import the unmutated venv install in the child, so a mutation
# sweep cannot kill a mutant in ``_expand_setrefs_for_iptables`` through
# them; these call the static method directly.
# ---------------------------------------------------------------------------


def test_expand_setrefs_replaces_value_with_elements() -> None:
    """A SetRef option value becomes its plain element list in place."""
    rule = Rule()
    rule.options.append(Option(name="dport", value=SetRef("p", ["22", "80"])))
    Parser._expand_setrefs_for_iptables(rule)
    assert rule.options[0].value == ["22", "80"]
    assert not isinstance(rule.options[0].value, SetRef)


def test_expand_setrefs_leaves_plain_options_untouched() -> None:
    """A non-SetRef option value is passed through unchanged."""
    rule = Rule()
    rule.options.append(Option(name="dport", value="22"))
    Parser._expand_setrefs_for_iptables(rule)
    assert rule.options[0].value == "22"


def test_expand_setrefs_rejects_two_sets_in_one_rule() -> None:
    """Two SetRef options in one rule is rejected before expansion."""
    rule = Rule()
    rule.options.append(Option(name="saddr", value=SetRef("a", ["10.0.0.1"])))
    rule.options.append(Option(name="daddr", value=SetRef("b", ["10.0.0.2"])))
    with pytest.raises(FermError, match="at most one named set"):
        Parser._expand_setrefs_for_iptables(rule)
