"""SetRef expands to cartesian product under the iptables backend."""

from __future__ import annotations

import pytest

from pyferm.errors import FermError
from pyferm.parser import Parser
from pyferm.scope import Option, Rule
from pyferm.values import Params, PreNegated, SetRef
from tests.unit._cli import run_pyferm


def _strip_generated_comment(text: str) -> str:
    """
    Remove the ``# Generated by ferm ...`` timestamp header line.

    The header embeds a wall-clock timestamp that differs between two
    back-to-back subprocess calls when they straddle a second boundary.
    Strip it before equality comparisons that care only about rules.
    """
    lines = text.splitlines(keepends=True)
    return "".join(
        line for line in lines if not line.startswith("# Generated by ferm")
    )


def test_setref_expands_like_literal_list() -> None:
    """A named set as a selector expands identically to a literal list."""
    with_set = run_pyferm(
        "@set $p = (22 80);\n"
        "domain ip table filter chain INPUT { proto tcp dport $p ACCEPT; }\n"
    )
    literal = run_pyferm(
        "domain ip table filter chain INPUT "
        "{ proto tcp dport (22 80) ACCEPT; }\n"
    )
    assert with_set.returncode == 0, f"set variant failed:\n{with_set.stderr}"
    assert literal.returncode == 0, (
        f"literal variant failed:\n{literal.stderr}"
    )
    assert _strip_generated_comment(
        with_set.stdout
    ) == _strip_generated_comment(literal.stdout), (
        "set variant output differs from literal:\n"
        f"--- set variant ---\n{with_set.stdout}"
        f"--- literal ---\n{literal.stdout}"
    )


def test_lone_parenthesised_set_ok() -> None:
    """Lone ``($p)`` is accepted and equals bare ``$p`` output."""
    with_parens = run_pyferm(
        "@set $p = (22 80);\n"
        "domain ip table filter chain INPUT "
        "{ proto tcp dport ($p) ACCEPT; }\n"
    )
    without_parens = run_pyferm(
        "@set $p = (22 80);\n"
        "domain ip table filter chain INPUT "
        "{ proto tcp dport $p ACCEPT; }\n"
    )
    assert with_parens.returncode == 0, (
        f"lone parenthesised set failed:\n{with_parens.stderr}"
    )
    assert without_parens.returncode == 0, (
        f"bare set failed:\n{without_parens.stderr}"
    )
    assert _strip_generated_comment(
        with_parens.stdout
    ) == _strip_generated_comment(without_parens.stdout), (
        "($p) and $p produce different output:\n"
        f"--- with parens ---\n{with_parens.stdout}"
        f"--- without parens ---\n{without_parens.stdout}"
    )


_MIXED_SELECTOR_CASES = [
    pytest.param(
        "@set $p = (80);\n"
        "domain ip table filter chain INPUT "
        "{ proto tcp dport (22 $p) ACCEPT; }\n",
        (),
        id="literal-before-set-iptables",
    ),
    pytest.param(
        "@set $p = (80);\n"
        "domain ip table filter chain INPUT "
        "{ proto tcp dport ($p 22) ACCEPT; }\n",
        (),
        id="set-before-literal-iptables",
    ),
    pytest.param(
        # backend-agnostic gate: the guard fires under --nft too
        "@set $p = (80);\n"
        "domain ip table filter chain INPUT "
        "{ proto tcp dport ($p 22) ACCEPT; }\n",
        ("--nft",),
        id="set-before-literal-nft",
    ),
    pytest.param(
        # regression for the _REF_TYPES omission that let the (22 $set)
        # ordering slip past the parse-time guard under --nft
        "@set $p = (80);\n"
        "domain ip table filter chain INPUT "
        "{ proto tcp dport (22 $p) ACCEPT; }\n",
        ("--nft",),
        id="literal-before-set-nft",
    ),
    pytest.param(
        # regression for the _read_array list-branch hole: a set followed by a
        # list variable silently emitted a @name rule plus a separate set rule
        # under --nft (where the iptables pre-pass does not run)
        "@def $hosts = (1.1.1.1 2.2.2.2);\n"
        "@set $p = (80);\n"
        "domain ip table filter chain INPUT "
        "{ proto tcp saddr ($p $hosts) ACCEPT; }\n",
        ("--nft",),
        id="set-before-list-nft",
    ),
    pytest.param(
        "@def $hosts = (1.1.1.1 2.2.2.2);\n"
        "@set $p = (80);\n"
        "domain ip table filter chain INPUT "
        "{ proto tcp saddr ($p $hosts) ACCEPT; }\n",
        (),
        id="set-before-list-iptables",
    ),
]


@pytest.mark.parametrize(("source", "flags"), _MIXED_SELECTOR_CASES)
def test_mixed_selector_rejected(source: str, flags: tuple[str, ...]) -> None:
    """A literal or list mixed with a named set in one selector is rejected."""
    proc = run_pyferm(source, *flags)
    assert proc.returncode != 0, f"expected rejection, got:\n{proc.stdout}"
    assert "mixed with other values" in proc.stderr, (
        f"expected 'mixed with other values' in stderr, got:\n{proc.stderr}"
    )


def test_nft_does_not_silently_expand_set() -> None:
    """
    Under --nft the nft backend renders SetRef as a @name reference.

    The iptables pre-pass (``_expand_setrefs_for_iptables``) is gated on
    ``not self.options.nft`` and does NOT run under ``--nft``.  Instead the
    nft backend translates the SetRef to a ``@name`` set reference rather
    than expanding it into concrete rules -- confirming the gate is real and
    the backends diverge intentionally here.
    """
    proc = run_pyferm(
        "@set $p = (22 80);\n"
        "domain ip table filter chain INPUT "
        "{ proto tcp dport $p ACCEPT; }\n",
        "--nft",
    )
    assert proc.returncode == 0, (
        f"nft SetRef translation failed:\n{proc.stderr}"
    )
    assert "@p" in proc.stdout, (
        f"expected @p reference in nft output, got:\n{proc.stdout}"
    )
    # The iptables pre-pass would have produced separate concrete rules
    # (one per element); confirm neither element appears as a standalone rule.
    assert "dport 22" not in proc.stdout, (
        "iptables-style expansion must not appear in nft output"
    )
    assert "dport 80" not in proc.stdout, (
        "iptables-style expansion must not appear in nft output"
    )


# ---------------------------------------------------------------------------
# In-process unit mirrors for the parse-phase pre-pass.  The subprocess
# cases above import the unmutated venv install in the child, so a mutation
# sweep cannot kill a mutant in ``_expand_setrefs_for_iptables`` through
# them; these call the static method directly.
# ---------------------------------------------------------------------------


def test_expand_setrefs_replaces_value_with_elements() -> None:
    """A SetRef option value becomes its plain element list in place."""
    rule = Rule()
    rule.options.append(Option(name="dport", value=SetRef("p", ["22", "80"])))
    Parser._expand_setrefs_for_iptables(rule)
    assert rule.options[0].value == ["22", "80"]
    assert not isinstance(rule.options[0].value, SetRef)


def test_expand_setrefs_leaves_plain_options_untouched() -> None:
    """A non-SetRef option value is passed through unchanged."""
    rule = Rule()
    rule.options.append(Option(name="dport", value="22"))
    Parser._expand_setrefs_for_iptables(rule)
    assert rule.options[0].value == "22"


def test_expand_setrefs_rejects_two_sets_in_one_rule() -> None:
    """Two SetRef options in one rule is rejected before expansion."""
    rule = Rule()
    rule.options.append(Option(name="saddr", value=SetRef("a", ["10.0.0.1"])))
    rule.options.append(Option(name="daddr", value=SetRef("b", ["10.0.0.2"])))
    with pytest.raises(FermError, match="at most one named set"):
        Parser._expand_setrefs_for_iptables(rule)


# ---------------------------------------------------------------------------
# match-set names an @set: no iptables expansion exists (ipset != nft set).
# ---------------------------------------------------------------------------


def test_match_set_setref_refused_under_iptables_cli() -> None:
    """`match-set $var` under the default backend refuses cleanly."""
    proc = run_pyferm(
        "@set $badguys = (10.1.2.3);\n"
        "domain ip table filter chain INPUT "
        "{ mod set match-set $badguys src DROP; }\n",
    )
    assert proc.returncode != 0, "expected match-set @set refusal"
    assert "@set cannot back an ipset name under the iptables backend" in (
        proc.stderr
    ), f"expected the match-set iptables message, got:\n{proc.stderr}"


def test_negated_match_set_setref_refused_under_iptables_cli() -> None:
    """The `! match-set $var` (PreNegated) form refuses the same way."""
    proc = run_pyferm(
        "@set $friends = (172.16.0.1);\n"
        "domain ip table filter chain INPUT "
        "{ mod set ! match-set $friends dst DROP; }\n",
    )
    assert proc.returncode != 0, "expected negated match-set @set refusal"
    assert "@set cannot back an ipset name under the iptables backend" in (
        proc.stderr
    ), f"expected the match-set iptables message, got:\n{proc.stderr}"


def test_expand_setrefs_refuses_params_nested_setref() -> None:
    """A SetRef buried in Params (match-set) refuses, does not expand."""
    rule = Rule()
    rule.options.append(
        Option(
            name="match-set", value=Params([SetRef("x", ["10.0.0.1"]), "src"])
        )
    )
    with pytest.raises(FermError, match="cannot back an ipset name"):
        Parser._expand_setrefs_for_iptables(rule)


def test_expand_setrefs_refuses_prenegated_params_nested_setref() -> None:
    """The PreNegated(Params([...])) form is refused too."""
    rule = Rule()
    rule.options.append(
        Option(
            name="match-set",
            value=PreNegated(Params([SetRef("x", ["10.0.0.1"]), "dst"])),
        )
    )
    with pytest.raises(FermError, match="cannot back an ipset name"):
        Parser._expand_setrefs_for_iptables(rule)


def test_expand_setrefs_counts_nested_setref_for_one_set_guard() -> None:
    """The one-set-per-rule count descends into the match-set Params."""
    rule = Rule()
    rule.options.append(Option(name="saddr", value=SetRef("a", ["10.0.0.1"])))
    rule.options.append(
        Option(
            name="match-set", value=Params([SetRef("b", ["10.0.0.2"]), "src"])
        )
    )
    with pytest.raises(FermError, match="at most one named set"):
        Parser._expand_setrefs_for_iptables(rule)
