import pytest

from pyferm.errors import FermError
from pyferm.plan import parse_save

_SAVE = """\
# Generated by iptables-save
*filter
:INPUT ACCEPT [10:800]
:FORWARD DROP [0:0]
:mychain - [0:0]
-A INPUT -c 5 200 -p tcp -j ACCEPT
-A INPUT -p udp -j DROP
-A mychain -j RETURN
COMMIT
"""


def test_parses_tables_chains_policies() -> None:
    tables = parse_save(_SAVE, host_mask="/32")
    assert set(tables) == {"filter"}
    chains = tables["filter"].chains
    assert chains["INPUT"].policy == "ACCEPT"
    assert chains["FORWARD"].policy == "DROP"
    assert chains["mychain"].policy == "-"


def test_strips_chain_and_rule_counters() -> None:
    chains = parse_save(_SAVE, host_mask="/32")["filter"].chains
    # -c 5 200 is dropped; [10:800] never reaches the chain
    assert chains["INPUT"].rules == ["-p tcp -j ACCEPT", "-p udp -j DROP"]
    assert chains["mychain"].rules == ["-j RETURN"]


def test_table_name_any_nonspace() -> None:
    tables = parse_save("*weird-table\n:X - [0:0]\nCOMMIT\n", host_mask="/32")
    assert "weird-table" in tables


def test_empty_input_is_empty_model() -> None:
    assert parse_save("", host_mask="/32") == {}


def test_comments_and_blanks_ignored() -> None:
    text = "# hi\n\n*filter\n:INPUT ACCEPT [0:0]\nCOMMIT\n"
    assert set(parse_save(text, host_mask="/32")) == {"filter"}


@pytest.mark.parametrize(
    "bad",
    [
        "-A INPUT -j DROP\n",  # -A before any *table
        ":INPUT ACCEPT [0:0]\n",  # :chain outside a table
        "*filter\nCOMMIT\n*filter\nCOMMIT\n",  # duplicate *table
        "COMMIT\n",  # COMMIT with no table
        "*filter\n:INPUT ACCEPT [0:0]\n",  # unclosed *table at EOF
        "*filter\ngarbage line\nCOMMIT\n",  # unrecognized line
        "*filter\n:bad chain ACCEPT [0:0]\nCOMMIT\n",  # chain name with space
        "*filter\n*nat\nCOMMIT\n",  # second *table before COMMIT
    ],
)
def test_malformed_raises(bad: str) -> None:
    with pytest.raises(FermError):
        parse_save(bad, host_mask="/32")
