"""Unit tests for :mod:`pyferm.domains`.

Covers the domain layer ported from ``reference/src/ferm`` (``:881-974``):
``find_tool`` in test mode and its ``*-legacy`` preference (incl. the
``--nolegacy`` deviation), the ``read_previous`` save parser, and
``initialize_domain``'s validation/idempotency/mock-previous paths plus the
injected ``eb`` atomic-save seam.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import pytest

from pyferm.config import Options
from pyferm.domains import (
    EB_TABLES,
    DomainInfo,
    find_tool,
    initialize_domain,
    read_previous,
)
from pyferm.errors import FermError

if TYPE_CHECKING:
    from pathlib import Path

# --- find_tool -------------------------------------------------------------


def test_find_tool_test_mode_returns_bare_name() -> None:
    # the reason golden output is path-independent (:883)
    assert find_tool("iptables-save", Options(test=True)) == "iptables-save"


def test_find_tool_prefers_legacy(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("PATH", "/bin")
    executable = {"/usr/sbin/iptables-legacy-save", "/usr/sbin/iptables-save"}

    def fake_access(path: str, _mode: int) -> bool:
        return path in executable

    monkeypatch.setattr("pyferm.domains.os.access", fake_access)
    # both exist, but the legacy spelling wins
    assert find_tool("iptables-save", Options()) == (
        "/usr/sbin/iptables-legacy-save"
    )


def test_find_tool_nolegacy_skips_legacy(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setenv("PATH", "/bin")
    executable = {"/usr/sbin/iptables-legacy-save", "/usr/sbin/iptables-save"}
    monkeypatch.setattr(
        "pyferm.domains.os.access", lambda p, _m: p in executable
    )
    # deviation #4: the legacy preference is bypassed, plain name resolves
    assert find_tool("iptables-save", Options(nolegacy=True)) == (
        "/usr/sbin/iptables-save"
    )


def test_find_tool_falls_back_to_plain_name(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setenv("PATH", "/bin")
    # only the non-legacy name exists
    monkeypatch.setattr(
        "pyferm.domains.os.access",
        lambda p, _m: p == "/sbin/iptables-save",
    )
    assert find_tool("iptables-save", Options()) == "/sbin/iptables-save"


def test_find_tool_not_found_raises(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("PATH", "")
    monkeypatch.setattr("pyferm.domains.os.access", lambda _p, _m: False)
    with pytest.raises(FermError, match="not found in PATH"):
        find_tool("nosuchtool", Options())


# --- read_previous ---------------------------------------------------------


def test_read_previous_records_tables_and_builtin_chains() -> None:
    dump = [
        "# Generated by iptables-save\n",
        "*filter\n",
        ":INPUT ACCEPT [0:0]\n",
        ":mychain - [0:0]\n",  # policy '-' -> not a builtin
        "-A INPUT -j ACCEPT\n",
        "COMMIT\n",
    ]
    info = DomainInfo()
    save = read_previous(dump, info)

    # text is returned verbatim for rollback
    assert save == "".join(dump)
    filter_table = info.tables["filter"]
    assert filter_table.has_builtin is True
    assert filter_table.chains["INPUT"].builtin is True
    # the '-' policy chain is not flagged builtin (and is never recorded here)
    assert "mychain" not in filter_table.chains


def test_read_previous_chain_before_table_is_ignored() -> None:
    # a chain line with no preceding *table has no table_info -> skipped
    info = DomainInfo()
    read_previous([":INPUT ACCEPT [0:0]\n"], info)
    assert info.tables == {}


# --- initialize_domain -----------------------------------------------------


def _noexec_execute(_command: str) -> int | None:
    raise AssertionError("execute must not run in these tests")


def test_initialize_domain_rejects_invalid_family() -> None:
    with pytest.raises(FermError, match="Invalid domain 'wat'"):
        initialize_domain(
            "wat", {}, Options(test=True), execute=_noexec_execute
        )


def test_initialize_domain_test_mode_tools_are_bare_names() -> None:
    domains: dict[str, DomainInfo] = {}
    initialize_domain(
        "ip", domains, Options(test=True), execute=_noexec_execute
    )
    info = domains["ip"]
    assert info.initialized is True
    # ip/ip6 get the save+restore tools; bare names under --test
    assert info.tools == {
        "tables": "iptables",
        "tables-save": "iptables-save",
        "tables-restore": "iptables-restore",
    }


def test_initialize_domain_arp_has_only_tables_tool() -> None:
    domains: dict[str, DomainInfo] = {}
    initialize_domain(
        "arp", domains, Options(test=True), execute=_noexec_execute
    )
    assert domains["arp"].tools == {"tables": "arptables"}


def test_initialize_domain_reads_mock_previous(tmp_path: Path) -> None:
    mock = tmp_path / "ip.save"
    mock.write_text("*filter\n:INPUT ACCEPT [0:0]\nCOMMIT\n", encoding="utf-8")
    options = Options(test=True, mock_previous={"ip": str(mock)})
    domains: dict[str, DomainInfo] = {}

    initialize_domain("ip", domains, options, execute=_noexec_execute)

    info = domains["ip"]
    assert info.previous == "*filter\n:INPUT ACCEPT [0:0]\nCOMMIT\n"
    assert info.tables["filter"].chains["INPUT"].builtin is True


def test_initialize_domain_missing_mock_previous_is_ferm_error() -> None:
    # The oracle's `open ... or die $!` (:948) is caught by check_domain's
    # eval and reported as a located ferm error; a raw OSError would
    # escape every FermError handler as a traceback.
    options = Options(test=True, mock_previous={"ip": "/nonexistent/save"})
    with pytest.raises(FermError, match="No such file or directory"):
        initialize_domain("ip", {}, options, execute=_noexec_execute)


def test_initialize_domain_is_idempotent() -> None:
    domains: dict[str, DomainInfo] = {}
    initialize_domain(
        "ip", domains, Options(test=True), execute=_noexec_execute
    )
    domains["ip"].tools = {"sentinel": "kept"}  # would be clobbered on re-init
    initialize_domain(
        "ip", domains, Options(test=True), execute=_noexec_execute
    )
    assert domains["ip"].tools == {"sentinel": "kept"}


def test_initialize_domain_eb_snapshots_each_table_in_order() -> None:
    calls: list[str] = []
    domains: dict[str, DomainInfo] = {}

    initialize_domain("eb", domains, Options(test=True), execute=calls.append)

    info = domains["eb"]
    try:
        # one atomic-save per table, in the fixed @eb_tables order
        assert list(info.ebt_previous) == list(EB_TABLES)
        assert [c.split(" -t ")[1].split()[0] for c in calls] == list(
            EB_TABLES
        )
        assert all("--atomic-save" in c for c in calls)
    finally:
        info.close()
