---
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'reference/doc/**'
      - 'reference/examples/**'
    branches: [main, master, develop, python-port]
  pull_request:
    paths-ignore:
      - 'reference/doc/**'
      - 'reference/examples/**'
    branches: [main, master, develop, python-port]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # frozen: v4.2.2
        with:
          persist-credentials: false

      - name: Install dependencies
        run: |
          sudo apt-get install -y --no-install-recommends \
            libnet-dns-resolver-mock-perl

      - name: Runt unit tests
        run: make -j"$(nproc)" -C reference check
